### ISSUE TITLE
Add TMS palette switch to Master System

### ISSUE THREAD

**Issue by MinecraftMario27** [irixxxx/picodrive#107]
Can you please add SG-1000 II mode in Master System Type option.
SG-1000 II allows 8KB RAM games for example: Taiwanese MSX Conversion on SG-1000 II, Korean MSX Ports on SMS
https://www.smspower.org/forums/13579-Taiwan8KBRAMAdapterForPlayingMSXPortsOnSG1000II

**Comment by irixxxx** [comment]
It basically is emulating an SG-1000 II with 2KB of RAM, as I didn't know of any game running only on the original SG-1000.
Is there any game requiring the original SG-1000 RAM setup?
Is there a problem with some SG-1000 II game you noticed?

**Comment by MinecraftMario27** [comment]
I try some few games

The Castle (Taiwan)

https://github.com/irixxxx/picodrive/assets/137607853/252e0138-efca-49d9-a159-3052ce5577bb

Castle Excellent (Taiwan)

https://github.com/irixxxx/picodrive/assets/137607853/bf6789c3-7dcf-4c7b-9e1e-4317da253f76

Bomberman Special (Taiwan)

https://github.com/irixxxx/picodrive/assets/137607853/83b3e7c6-e140-43cf-a72b-03c5a5e3a165

Super Boy I (Korea)

https://github.com/irixxxx/picodrive/assets/137607853/613688a6-9b51-47de-9405-d50a9587c183

Super Boy II (Korea)

https://github.com/irixxxx/picodrive/assets/137607853/2b7259d6-aa9a-4f2b-b0d6-117144e257c5

Super Boy 3 (Korea)

https://github.com/irixxxx/picodrive/assets/137607853/b479fea4-097d-41ea-87dd-5b48ddb58a44

**Comment by irixxxx** [comment]
Correct me if I'm wrong, but aren't some of those SMS games? At least smspower.org doesn't have Super Boy games listed for SG.
Could you please try running those games with the system set to Master System?

**Comment by MinecraftMario27** [comment]
> Correct me if I'm wrong, but aren't some of those SMS games? At least smspower.org doesn't have Super Boy games listed for SG. Could you please try running those games with the system set to Master System?

- On Master System mode uses dark color but that is how they runs on real Master System hardware. Master System/Mark III is backward compatibility with SG-1000
- SG-1000 actually uses original TMS9918 color palette. Actually, SG-1000 has 1KB or 2KB of RAM
- It looks like those a Master System game but it uses TMS9918 mode and They need 8KB present of the RAM.

**Comment by MinecraftMario27** [comment]
> Correct me if I'm wrong, but aren't some of those SMS games? At least smspower.org doesn't have Super Boy games listed for SG. Could you please try running those games with the system set to Master System?

Those aren't SMS games. It actually uses TMS9918 mode. Super Boy I, Super Boy II, Super Boy 3 uses .sms file extension as Master System game but it's actually TMS9918 mode display. Master System / Mark III is backward compatibility with SG-1000

When I set to Master System mode or Auto but it's dark colors. That is how they looks on real Master System / Mark III hardware.

TMS9918 mode can't be displayed on Game Gear and Genesis/Megadrive hardware and it displays black screen

**Comment by irixxxx** [comment]
So this is not about SG-1000 II but either:
- have an additional 8KB RAM adapter emulated in SG-1000 which has RAM from 0xc000 to 0xe000?
- have a palette selection switch for SMS games running in TMS modes?

**Comment by MinecraftMario27** [comment]
Yes

**Comment by irixxxx** [comment]
I'll go with the palette selection as this is much easier to do ;-)

**Comment by irixxxx** [comment]
added with 214a6c6
