### ISSUE TITLE
Run very well on Powkiddy Q90/V90 but can't exit game or access menu during gaming

### ISSUE THREAD

**Issue by Baodejia** [irixxxx/picodrive#111]
Hello, thank guys for your works , run very well on Powkiddy V90/Q90 with CFW 1.3.3 and 2.0 beta but can't exit game or access menu during gaming

**Comment by irixxxx** [comment]
Could you check in the options/controls/hotkey menu which key is bound to the "enter menu" function?
What's happening when you hit the configured menu key?

**Comment by Baodejia** [comment]
Thank you for response, I will check this tonight

**Comment by Baodejia** [comment]
With Custom firmare 1.3.3
q90 and v90
Without any setting on screen "enter menu" is mapped on "R" with this setting cannot access menu during game or exit game

On Q90 when i set "enter menu" and i press "-" button, on screen it is writed "enter menu:reset"
, i save the global config and launch a game and it work, when i press (-) button i can access the menu during game and exit the game, i tested it on V90 it works too.

PS with Q90 (+) button no mappable and with V90 L2 and R2 not mappable.

Now i will try with Miyoo Custom Firmware 2.0 beta
Thank you sir

**Comment by Baodejia** [comment]
With Custom firmare 2.0 beta for Q90 selected (it seems this cfw version have some problems with button configuration)
result on Q90 and V90
On screnn "enter menu" is mapped on "Select" with this setting we can access menu during game or exit game when pressing "select" button


On v90 
when i press "menu" button to map it to "enter menu it show on screen "L2" with this setting we cannot access menu during game or quit  
when i press "R2" button to map it to "enter menu it show on screen "Reset"  with this setting we can access menu during game or quit
when i press "L2" button to map it to "enter menu it show on screen "R2" with this setting we can access menu during game or quit

on Q90
when i press "-" button to map it to "enter menu it show on screen "L2" with this setting we cannot access menu during game or quit  
when i press "+" button to map it to "enter menu it show on screen "Reset"  with this setting we can access menu during game or quit



With Custom firmare 2.0 beta for V90 selected (no problem with button configuration)
result on Q90 and V90
On screnn "enter menu" is mapped on "Select" with this setting we can access menu during game or exit game when pressing "select" button


On v90 
when i press "menu" button to map it to "enter menu it show on screen "Reset" with this setting we can access menu during game or quit  
when i press "R2" button to map it to "enter menu it show on screen "R2"  with this setting we can access menu during game or quit
when i press "L2" button to map it to "enter menu it show on screen "L2" with this setting we can access menu during game or quit

on Q90
when i press "-" button to map it to "enter menu it show on screen "Reset" with this setting we can access menu during game or quit  
when i press "+" button to map it to "enter menu it show on screen "R2"  with this setting we cannot access menu during game or quit

PS with Q90 (+) button is mappable and with V90 L2 and R2 are mappable.

**Comment by Baodejia** [comment]
some 2d game in 256x224p are not stretched to full screen

**Comment by irixxxx** [comment]
> some 2d game in 256x224p are not stretched to full screen

This isn't exactly a bug. See issue #59 for the full explanation of the issue, but the gist is I'm trying to keep the right aspect ratio. Albeit the SMS screen has only 192 lines in its display area, it still needs to display 224 resp. 240 lines.

**Comment by irixxxx** [comment]
Seems like I goofed while revisiting the button handling. I'm going to check this on my V90.

**Comment by irixxxx** [comment]
Can you please check that this line is in .picodrive/config2.cfg on the main partition:
``bind SELECT = Enter Menu``

**Comment by irixxxx** [comment]
Please throw your config2.cfg file away and check if it works with the built-in defaults.

**Comment by irixxxx** [comment]
Since there's no more activity and it works fine on my V90: closed.
