### ISSUE TITLE
Minor issue - Emulator crashes when loading Oh Mummy Genesis from GMENU2X (MiyooCFW)

### ISSUE THREAD

**Issue by veb-xenon** [irixxxx/picodrive#112]
I'm very happy with last 2.0 Alpha 3 which I'm testing in native mode for Mega Drive and Mega CD games on my Powkiddy Q90 and V90. I'm using 1.33 CFW but updating all the emulators I have.

I've checked that if I load "Oh Mummy Genesis" from the menu (GMENU2X) the emulator just hangs and it exits. But if I load the game from the internal emulator menu, it runs flawlessly. It's the only game for now that I've found that it can't be load from the CFW.

Just for your information :-)

**Comment by irixxxx** [comment]
Could you please try if the latest version from the Actions page is still exhibiting this behaviour?

**Comment by veb-xenon** [comment]
Yes, I've tested with last https://github.com/irixxxx/picodrive/actions/runs/7908554284 , and it shows all games loading but it quits inmediately.

**Comment by veb-xenon** [comment]
Just for your information, I've tested the last four builds from Actions just don't execute any game 😞. Emulator runs, but if you load any game, from the file selector or the internal loader, it just hangs and exits.

**Comment by irixxxx** [comment]
It's crashing if the sound rate is 0. What's it showing you in the sound menu? Try setting it to something else.

**Comment by veb-xenon** [comment]
I've tried with 44100 and 22500. It still crashes when loading a game.

**Comment by irixxxx** [comment]
It can't be a general problem, it works on a generic linux version which is by and large the same code.
I'll try to check tonight with a Q90 on 2.0.0 CFW.

BTW the originally reported game also runs perfectly fine both through command line and menu on the generic version.

**Comment by irixxxx** [comment]
It's a problem with the arm assembly. Please check with current master build.

**Comment by veb-xenon** [comment]
Checked https://github.com/irixxxx/picodrive/actions/runs/7993626585 (bfe516c). Oh Mummy resists to load from the MiyooCFW 1.3.3 launcher, but emulator runs well and stable :-)

Another game I've found a strange problem is Sonic Compilation. If you select Sonic 1 game hangs. Fortunately these are small issues. Emulator overall is better than ever!

**Comment by irixxxx** [comment]
Fixed by ad43165. The reset defaults for the Z80 cpu were wrong.
Please check with the latest action build.

**Comment by veb-xenon** [comment]
Excellent! Now Oh Mummy runs well from the launcher. So you can close this issue. Thanks very very much!
