### ISSUE TITLE
Picodrive/config2.cfg info for picodrive 2.0

### ISSUE THREAD

**Issue by Baodejia** [irixxxx/picodrive#114]
Hello, as requested, i checked .picodrive/config2.cfg to verify if  "bind Select=Enter Menu".
I found this in the config2.cfg "bind RESET = Enter Menu"

**Comment by irixxxx** [comment]
replace the RESET by SELECT and try to enter the menu with the SELECT key on your device.
If this is working for you, got to options/controls/hotkeys and list me the key bindings listed there.

**Comment by irixxxx** [comment]
Please try removing config2.cfg altogether and check if the keys behave normally after that.
