### ISSUE TITLE
musashi cpu core is broken

### ISSUE THREAD

**Issue by notaz** [irixxxx/picodrive#115]
`cpu/musashi` used to be the fallback for non-arm32 hw until fame appeared. It's possible to force to use it with
```
make use_musashi=1 use_cyclone=0 use_fame=0
```
It's still working in my repo. If you don't plan to maintain it I think it would be good to remove it.

**Comment by irixxxx** [comment]
It used to work. I rarely use it, but still... I'll have a look.

**Comment by irixxxx** [comment]
Could you please check if my musashi branch solves your problems?

**Comment by notaz** [comment]
Works, thanks.

**Comment by irixxxx** [comment]
moved to master.
