### ISSUE TITLE
Windows Defender - Virus Alert (False Positive, of course)

### ISSUE THREAD

**Issue by veb-xenon** [irixxxx/picodrive#119]
For your information, after downloading 5adcc16 (master), Windows Defender (Windows 11) blocks the zip I've downloaded (Miyoo.zip), even I know that it's clean. It detects a "Trojan:Script/Wacatac.B!ml" virus, and I know of course that it's a false positive.

If I download the GP2X files, Windows Defender does not detect anything. So strange :-/ . Same happens with v2.00-beta1 Miyoo, no issues.

![imagen](https://github.com/irixxxx/picodrive/assets/62928707/5b5de2cf-f367-4b95-b4bc-5ac5f6148308)

**Comment by irixxxx** [comment]
Huh... I'm not sure I can do anything about it?

**Comment by veb-xenon** [comment]
No problem, just if somebody asks or complains, I wanted to inform you :-) . I've decompressed the file in my Powkiddy MicroSD, and now I'm enjoying the emulator.

**Comment by irixxxx** [comment]
Thanks anyway. I really hope you enjoy it.
