### ISSUE TITLE
No audio on RG350P running ODBeta

### ISSUE THREAD

**Issue by FatehAK** [irixxxx/picodrive#123]
Hey @irixxxx thanks for the emulator. I'm trying to set it up on a RG350P running ODBeta. It's running smoothly but there is no audio. I've tried multiple games in '.md' format but all have the same issue. Could you please help in checking?

I'm using the latest v2.00-beta2 version of the emulator

![image](https://github.com/irixxxx/picodrive/assets/34565559/346f952e-0a26-48bd-bb27-794e8d74aee6)

**Comment by irixxxx** [comment]
I'll check this on my gcw0.
Meanwhile, could you possibly check if prior alpha/beta versions of 2.00 worked?

**Comment by irixxxx** [comment]
After not having success to reproduce this on a gcw0, I got myself an rg350p and tried adam 1.4.2, adam 2.1, as well as odbeta 2022-09-22 and 2024-04-03. Audio is there on all versions. What build date is your odbeta reporting in the settings/about opk?

**Comment by irixxxx** [comment]
No success in reproducing this by me or others. @FatehAK please provide more information about the OD version you are using. Also consider updating to a newer version. You can obtain those from the opendingux github page, either from the release tags section or from the Actions tab (make sure you get one from the opendingux branch).

**Comment by irixxxx** [comment]
Closing since it is not reproducible by me or others, and no responses in several weeks.
