### ISSUE TITLE
[BUG]: Some Sonic games (with lock-on technologies) do not work well.

### ISSUE THREAD

**Issue by raptor264** [irixxxx/picodrive#126]
The following sonic games don't work well:
-Sonic & Knuckles (World)
-Sonic & Knuckles + Sonic The Hedgehog (USA, Europe) (Lock-on Combination).
-Sonic & Knuckles + Sonic The Hedgehog 2 (World) (Rev A) (Lock-on Combination).bin
-Sonic & Knuckles + Sonic The Hedgehog 3 (USA) (Lock-on Combination).bin
-Sonic The Hedgehog 3 (USA)

errors include black screen and/or audio errors. 
They don't have checksum errors because I fixed them.

**Comment by irixxxx** [comment]
I just a bug around audio in my master. Could you please retry with the latest version from the Actions tab?

**Comment by DrUm78** [comment]
That definitely fixes Sonic & Knuckles on x86_64 and armv7 for me. 👍

**Comment by raptor264** [comment]
Now it works. There are no problems in any game. Well done!.

**Comment by irixxxx** [comment]
Fixed by db2b6d9
