### ISSUE TITLE
PSP build shutdown the console when browsing multiple folders.

### ISSUE THREAD

**Issue by wikiblog0** [irixxxx/picodrive#127]
Hello

I was testing the new version of Picodrive (v2.00 beta 3) on my psp, but when I browse more than 2 directories the console was shutting down. I had to move my roms folder to the root of the SD card to avoid that error. The games run fine. I ran the PSP build on a PSP 1000.

I wanted to see if this problem was when running the PSP build on the PPSSPP PC and Wii U emulator. In both versions of the emulator, I saw that when I browsed more than two directories the screen would go black but if I selected a random folder I would see an image again. I want to emphasize that the screen went black every time I moved every two directories. 

I don't know if in a PSP 2000/3000 persists the shutdown error that occurs in the PSP 1000 or has the black screen error that happened in the PPSSPP emulator.

Regards.

**Comment by irixxxx** [comment]
I have tried to reproduce the bug in ppsspp but no luck. Could you maybe provide a video?

**Comment by irixxxx** [comment]
Which OS version is installed on your PSP?

**Comment by irixxxx** [comment]
It's a bug in pspsdk, which I use to compile the psp version. Fix by @fjtrujy is under way.

**Comment by irixxxx** [comment]
Fixed in pspsdk. Will be automatically in the next CI builds.

**Comment by wikiblog0** [comment]
Hi 

I want to apologize for not answering, I was away from home and until now I had time to see if my problem had been read. I was able to test the latest CI build of Picodrive in PPSSPP for Windows and the problem no longer exists. I have not been able to test on my PSP but I will soon. Many thanks to you and @fjtrujy for solving the bug in the PSP build.
Regards.
