### ISSUE TITLE
Summary of Changes Post-Fork

### ISSUE THREAD

**Issue by carmiker** [irixxxx/picodrive#13]
I am posting this issue to suggest creating some sort of change log between the original PicoDrive and this fork. It seems the original is not very active, but much work has been done here. It would make it easier for the casual observer to know exactly what has changed, by having it all in one easy to read place instead of looking through the commit history.

Great work by the way, and I look forward to seeing continuous improvements.

**Comment by irixxxx** [comment]
I'll put this on the back burner for one of the next releases...

**Comment by irixxxx** [comment]
In case this is still of interest, there are now change lists for each release on the release page.
