### ISSUE TITLE
Sound disappears after a few seconds on PS2

### ISSUE THREAD

**Issue by UsagiRu** [irixxxx/picodrive#135]
Hello, firstly thank you for the incredible work, I would like to report an error, when playing any game, regardless of the emulated system, the sound disappears, when entering and exiting the menu returning to the game the sound returns, and disappears again.

**Comment by irixxxx** [comment]
Which audio settings did you use, rate, stereo?
PAL or NTSC?

**Comment by UsagiRu** [comment]
Thanks for your attention, the problem was solved by leaving it at 44100Hz :D

**Comment by irixxxx** [comment]
I'll take a look at it. On older devices like ps2 it's quite nice to gain some additional speed by reducing the sound rate.

**Comment by irixxxx** [comment]
Would you please check if sound works with the latest CI build from the Actions tab for branch ps2_audio

**Comment by UsagiRu** [comment]
It worked perfectly, without any additional configuration, thank you very much!!

**Comment by UsagiRu** [comment]
Not wanting to abuse your kindness, I can make a suggestion?  Many PS3 and PS4 users use homebrew and PS2 emulators, but to do so it would be necessary for the emulator to work in the .ISO format, do you believe this could be possible?

**Comment by irixxxx** [comment]
Fixed by 75db61b.

As for making an ISO, I'll ask @fjtrujy if ps2sdk has an easy way to generate one.

**Comment by irixxxx** [comment]
I've replacement the ps2 binary in the release section, so any further downloaders get the fixed version.
