### ISSUE TITLE
(PS2) Second joystick does not respond to commands

### ISSUE THREAD

**Issue by UsagiRu** [irixxxx/picodrive#138]
Hello again :3 
There is no way to play with 2 players, the second controller is not recognized in any way, even in the button remapping session only the commands from the first joystick are recognized

**Comment by irixxxx** [comment]
Have you tried the latest version from the actions tab?
I did some work to add another controller. It's not yet tested though.

**Comment by UsagiRu** [comment]
Works great! Thanks!! <3

**Comment by UsagiRu** [comment]
Thank you very much! The controls now work fine, but in this latest version there is still a previous sound bug :,v

**Comment by UsagiRu** [comment]
Thank you very much! The controls now work fine!!

**Comment by irixxxx** [comment]
added with bba9929
