### ISSUE TITLE
[BUG-PS2] Control not work in game

### ISSUE THREAD

**Issue by mariamariasilva1933** [irixxxx/picodrive#144]
i try the latest build action PS2
control work in menu but in game not work proper
buttons work more d-pad not work.
d-pad keeps going left alone

**Comment by irixxxx** [comment]
Try remapping the buttons for player 1 in the configuration. It should work afterwards.

**Comment by mariamariasilva1933** [comment]
i try and no work, in picodrive menu work, with game running no. ty bro

**Comment by irixxxx** [comment]
Could you please check with the latest build for the ps2 branch in the actions tab? That should fix this, and also have support for L2/r2 and L3/R3.

**Comment by mariamariasilva1933** [comment]
PS2 have only L1//R1 and L2/R2, tested now its all ok
new bind add sucess and control d-pad bug solved sucess.
the game blackthorn sega 32x is possible improve sound and gameplay ?
the game final fight cd Europe not work
i go test USA version now.

TY cheers!!!

**Comment by mariamariasilva1933** [comment]
in PS2 L3/R3 is when press the analog for down ?

**Comment by irixxxx** [comment]
It's enabled the same way as the other L/R buttons, but maybe there's more to it. Doesn't matter for now, I guess. Thanks for the Feedback!

**Comment by mariamariasilva1933** [comment]
u need feedback i can help you, ty

**Comment by irixxxx** [comment]
I'd probably need to enable the analog part of the controller to get L3/R3 to work. That's currently not planned, hence I'm inclined to ignore L3/R3 altogether for now.

BTW the latest build also contains code to support 4 controllers with a multitap. If you have a setup to test that, go ahead please. There's also some very preliminary support for J-Cart.

**Comment by mariamariasilva1933** [comment]
sega 32x is possible improve to run with soun and less lag ?

**Comment by irixxxx** [comment]
I'm afraid the CPU of the PS2 is just not fast enough to emulate the complex CPU arrangement used with the 32X (a total of 4 CPUs). I've however not done specfic optimisation for PS2. There might be some gain in that.

**Comment by irixxxx** [comment]
fixed in libpicofe:86a086e in with 32d9484
