### ISSUE TITLE
[Build] Cannot compile using SDL2

### ISSUE THREAD

**Issue by mondul** [irixxxx/picodrive#146]
As I already have the `libsdl2-dev` package installed, I ran the configure script as `SDL_CONFIG=$(which sdl2-config) ./configure --platform=generic` and it succeeded. After running `make` the following error was thrown:

```
...
In file included from platform/common/plat_sdl.c:14:
platform/common/../libpicofe/plat_sdl.h:4:8: error: unknown type name 'SDL_Overlay'
    4 | extern SDL_Overlay *plat_sdl_overlay;
      |        ^
...
```

Also, fixing this will allow building for macOS :-)

**Comment by irixxxx** [comment]
As it is Picodrive doesn't have direct support for compiling with sdl2. You can however using the sdl1 compatibility layer with sdl2, e.g. Picodrive compiles fine under OSX using brew like this:

`brew install sdl2 sdl12-compat`
`CFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib" SDL_CONFIG=/opt/homebrew/bin/sdl-config ./configure`

The same works fine under Linux as well.
