### ISSUE TITLE
Castlevania Bloodlines crashes at Stage 6 on RG353V

### ISSUE THREAD

**Issue by JosepMC154** [irixxxx/picodrive#147]
Using [ArkOS](https://github.com/christianhaitian/arkos), RA core version "2.01-0daf92b5", 64-bit. 

PicoDrive boots me out of Castlevania Bloodlines right at the final stage. Once the playable character walks to the middle of the screen, RA just closes and boots me back to the main menu. This behavior does not happen with the same emulator on my other devices (PC, Xbox Series S, Odin Lite, etc).

Does not happen with Genesis Plus GX and the 32-bit version of PicoDrive on the same device, though ArkOS' maintainer says he hasn't updated that very version in awhile.

**Comment by irixxxx** [comment]
Please add md5sum of game and a save state file from shortly before the crash. Instructions what to do after loading the state might also be helpful.

**Comment by JosepMC154** [comment]
You can load the stage through the [password feature](https://www.vgmuseum.com/mrp/code-bl.htm). The MD5 of the US ROM is "0f04fc1b5bf8c9a887abcf14ce96b0cd", but I also tried the Japanese version (Vampire Killer) and it happens there as well.

The game just crashes as soon as John/Eric gets to the middle of the screen. I can record a video if you prefer.

**Comment by irixxxx** [comment]
Could you please check if this is also happening with the windows?

**Comment by JosepMC154** [comment]
> Could you please check if this is also happening with the windows version?

Do you mean on PC? It doesn't happen there, nor it does on Xbox Series S or my Android ARM devices, which makes me think something might be off when running it through this device somehow.

**Comment by irixxxx** [comment]
That would make it extremely difficult to analyse. I don't own such a device.

Do you by any chance by any chance have access to an apple device running OSX with an ARM CPU?

**Comment by irixxxx** [comment]
I'm tied up in November. I'll deal with it next month.

**Comment by irixxxx** [comment]
Could you please check if this is still the case with the current master branch?

**Comment by JosepMC154** [comment]
It seems to work fine now, much appreciated. 

Also, many thanks for still maintaining and further improving PicoDrive.
