### ISSUE TITLE
Tag 1.98 release

### ISSUE THREAD

**Issue by rtissera** [irixxxx/picodrive#15]
Can you tag 1.98 release after dust has settled a bit around potential remaining issues ?

**Comment by irixxxx** [comment]
yes. I'll do release builds and publish them, that will need a tag anyway.
I hesitate doing this right away to see if something severe comes up. Nonetheless I'll do this tomorrow evening to give users something to play with over Easter.

**Comment by irixxxx** [comment]
tag is set. I needed to include two hot fixes for an sh2 drc bug on x86 and a speed regression on arm devices. You might want to include these in your work.

**Comment by rtissera** [comment]
thanks a lot, great work as always
