### ISSUE TITLE
"SH2 cycles" option is broken

### ISSUE THREAD

**Issue by notaz** [irixxxx/picodrive#153]
Changing it and returning to game doesn't have any effect, as well as saving config and restarting. This used to work pre-fork, should be dropped from the menu if this is intentional.

**Comment by irixxxx** [comment]
Are you sure that is still the case with 2.02? I thought I fixed it with the latest commit.

**Comment by irixxxx** [comment]
No, it's indeed broken. The function in 32x.c is using some constants instead of the config values. So much for last minute changes :-/

I'll fix this in the next days

**Comment by irixxxx** [comment]
fixed with 071a9e5
