### ISSUE TITLE
Corrupted graphics in Dragon Ball: Final Bout unlicenced pirate game

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#17]
Hello. There exists an unlicenced Mega Drive game that works perfectly fine in Kega Fusion, Genesis Plus GX, possibly BlastEm, yet under Picodrive 1.98, character selection screen looks like this:

![Przechwycenie obrazu ekranu_2021-04-06_13-49-23](https://user-images.githubusercontent.com/32672779/113706824-687fa000-96df-11eb-893e-97ce7ec02367.png)

Rest of the game seems to work OK, but I didn't test everything in depth.

**Comment by irixxxx** [comment]
Confirmed. I'll have a look.

**Comment by irixxxx** [comment]
A lost interrupt leads to a misguided data transfer to video RAM.

**Comment by irixxxx** [comment]
fixed with 02d753e
