### ISSUE TITLE
Minor RetroFW QOL Changes

### ISSUE THREAD

**Issue by Cralex** [irixxxx/picodrive#19]
Hello,
The current release is running great on my LDK running RetroFW. There are a couple things that would make it better, though.

- The file filter is missing .chd support, so Sega CD games in .chd format won't appear by default in gmenu.
- The default Section is set to "games", which causes it to appear alongside native games ported to the system in gmenu. It would be easier to find if it was set to "emulators", which would place it with the other emulators.

Both changes can be easily made by the user if they know how, so this is far from being a critical issue. Thanks for the release!

**Comment by irixxxx** [comment]
Thanks for the feedback. Fixed with 8b48f9d.
