### ISSUE TITLE
Screen scaling on RG350M

### ISSUE THREAD

**Issue by Medard22** [irixxxx/picodrive#21]
The latest version PicoDrive-opendingux_1.98.opk doesn´t work well on my RG350M, the output is not scaled at all. It shows a small window in the middle of the screen. There is no option to scale the output to fullscreen.

**Comment by rchrdcrg** [comment]
Are you on the OpenDingux Beta or on another firmware like stock 1.5.1 or Rogue?

**Comment by Medard22** [comment]
Stock firmware with HDMI update from here - https://github.com/retrogamehandheld/rg350m/wiki/Firmware-and-software-updates

**Comment by irixxxx** [comment]
I've just checked the release opk on my rg350m. It's working as expected, however I don't have the HDMI version, just the stock  firmware that came with the device. What exactly isn't scaled for you?

**Comment by Medard22** [comment]
It seems to run in 320x240 resolution and doesn´t scale at all. Only possible output is SDL window.
![IMG20210428125451](https://user-images.githubusercontent.com/42897361/116393187-9a3ce000-a821-11eb-97c6-13d96dcbe672.jpg)

**Comment by irixxxx** [comment]
Picodrive just uses the resolution offered by the device which in my case is 320x240. Upscalig to screen resolution is handled automatically somewhere else. That leaves the question why your device is defaulting to the screen resolution.

**Comment by Medard22** [comment]
I have no idea, but the 1.97 release works fine.

**Comment by irixxxx** [comment]
It doesn't seem to be possible to detect whether there is hardware scaling available. Just setting the resolution of the emulator screen to 320x240 fails on some platforms, sometimes even without returning an error - the screen is just black or distorted in that case.
Would a setting to set the "SDL window resolution" to either "default" or "320x240" be an acceptable solution? The menu screen would in that case always use the default resolution to avoid a failed menu display.

**Comment by zeroix15** [comment]
are you using simple menu to launch the emulator? 
this is one of the reason why the screen is not scaled properly
try launching it direcly from gmenu2x

**Comment by Medard22** [comment]
I am using Esoteric. I will try to launch it from gmenu2x later on.

**Comment by irixxxx** [comment]
I've added a currently invisible option to set the screen format to 320x240 in SDL window mode. Are you able to compile a version for rg350? I can supply information about enabling the option.

**Comment by Medard22** [comment]
@zeroix15 was right. When launched from gmenu2X the scaling works perfectly. The problem is only when I launch it via Esoteric. I wonder why it´s so. I use the standard 320x240 resolution and don´t use any high-resolution skin.

@irixxxx Sorry I really don´t know how to compile it. I could try to set it up if you give me instructions. Or, if you send me the opk , I can test it right away.

**Comment by zeroix15** [comment]
if that's the case then its the bug on esoteric,
it also happen at the old version of simplemenu, but fixed after an update from the devs

**Comment by Medard22** [comment]
Damn, that's bad. Esoteric doesn't look like it´s being actively developed anymore. I guess I can´t expect them to fix it on their side.

**Comment by Medard22** [comment]
@irixxxx Works great. Fixed :)

**Comment by irixxxx** [comment]
I've reworked the larger part of the scaling logic with d5d1778, adding software scaling and some handling for correct display aspect ratio. I sincerely hope this is finally solved ;-)
