### ISSUE TITLE
[MCD] Lack of FM SFX in Sonic CD 0.02 proto build

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#22]
This issue is _very_ specific, down to just[ one version of one game](https://hiddenpalace.org/Sonic_the_Hedgehog_CD_(Dec_4,_1992_prototype)) (but still, it can be present in other titles or builds of Sonic CD). While the CD-DA tracks are playing fine, sound effects like jumping etc. are silent, when they shouldn't be. Unless I'm mistaken, the game uses FM synth for sound effects. What's weirder, final build of Sonic CD works perfectly, with all audio intact.

It's not a big deal personally, just wondering what's causing this behaviour.

**Comment by irixxxx** [comment]
Old bug, this is so since at least 1.93.

**Comment by irixxxx** [comment]
Weird, both 68k cpus are operating, but there is absolutely no access to the ym2612 after starting the game.

**Comment by irixxxx** [comment]
fixed with ca8b001. Pretty cool bug BTW - the code relies on the fact that a Z80 reset doesn't reset the registers
