### ISSUE TITLE
[RG350M ]1.98 release doesn't work on a new OpenDingux beta

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#24]
As expected. Not a big deal to me, just letting you know - selecting a ROM causes a crash back to ROM selection menu.

**Comment by irixxxx** [comment]
Is there something I should/could do about this?

**Comment by freq-mod** [comment]
This program would have to be compiled with the new toolchain to work on the new OD.

**Comment by irixxxx** [comment]
Now I remember why I haven't used the OD toolchain - IIRC it only works on Ubuntu 20+, while I'm tied to an older version for a part of the toolchains I use :-/

**Comment by irixxxx** [comment]
Published pre-release 2.00-alpha1. There are 2 odbeta builds for lepus and gcw0. So, if anybody has one of these 2 devices running with odbeta, please try this and report back here!
