### ISSUE TITLE
Z80 sound crash in Overdrive 2 techdemo

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#25]
I know it might be out of scope of this emulator to ask about it, since it's meant to be more fast than 100% accurate, but anyway:

Overdrive 2 demo, while working **much** better than before the fork, has one problem: towards the end part, sound crashes. It either flatlines or goes silent. The rest of demo plays normal, though.

I don't recall it acting this way before the fork, the sound was playing till the very end (my memories may fail me)

**Comment by DrUm78** [comment]
Yep, irixxxx is aware of that. But still nice to have it in a ticket for sure.

**Comment by irixxxx** [comment]
Yes, I know. I can't get the timing right for this. Apparently the 68k is not fast enough in writing further audio data to the z80 ram, which then crashes. Is the 68k running too slow or the z80 running too fast? That eludes me as of now.

**Comment by irixxxx** [comment]
I've just checked, v1.93 behaves the same soundwise. If it ever worked, it must've been before that.

**Comment by irixxxx** [comment]
Finally. Fixed with 134092f.
