### ISSUE TITLE
Demons of Asteborg fails initializing sram, and save state doesn't work between boots

### ISSUE THREAD

**Issue by asoderq** [irixxxx/picodrive#26]
Hi,

a newly released game for sega genesis/mega drive called Demons of Asteborg has a few problems. md5sum:
8c78f0ccd4a9006546d9f16cf11c5029

1. While it does boot, it fails to initialize sram.
2. Using save states only works within the same run, if you exit the emulator and restart the game and load the state the game is somehow corrupt: it does load but sound is bugged and when trying to enter next screen you get either glitchy graphics or black screen.

**Comment by irixxxx** [comment]
Yes, I know there are some problems with saving/loading games. It's on my list for the next release.

**Comment by asoderq** [comment]
This commit supposedly fixes the sram issue:
https://github.com/libretro/picodrive/commit/4867a33c8f455b9534b8f004dc9de3a21cad9daa

**Comment by irixxxx** [comment]
oh super, I somehow missed that one. thx.
I'm currently doing some work on the save/load stuff in general. If anyone has reproducible examples for failure I'd appreciate some info.

**Comment by asoderq** [comment]
Demons of Asteborg should suffice if you want something reproducible.
1. Go into gameplay, where you control the character.
2. Create a save state.
3. Exit emulator. (This might not be necessary)
4. Restart game
5. Load state from introduction screen.
6. This will result is glitchy graphics with no background.

A potential work around is, which I haven't tested myself, but it might give you a hint of what is wrong:
1. Go into the gameplay where you control the character.
2. Load state from there.
3. Should result in correct behavior.
This has been reported from other users to be a workaround for save states.

**Comment by irixxxx** [comment]
Sorry for having been a bit too vague. Here's a slightly better explanation:
These mappings for EEPROM/SRAM, or ROM banking, heavily depend on the hardware inside the cartridges, and that can differ. Picodrive already has a set of mapping for some titles, but I reckon it's not complete.

So: if anyone knows about other titles with symptoms from my above list, please drop me a note. This mostly shows pretty early, in the intro or in lower levels. Like I said, totally garbled graphics or audio, not booting, crashing, non-working save/load, ...

**Comment by irixxxx** [comment]
Initial issue fixed with e370f4d. Credits (and my thanks) go to madmonkey1907 for fixing this!
