### ISSUE TITLE
Battery saves not supported for Master System games

### ISSUE THREAD

**Issue by Coolie2** [irixxxx/picodrive#30]
In testing in-game save functionality for all of the default emulators of the FunKey S, I noticed that PicoDrive, the default emulator used for Master System emulation, did not support the battery save functionality of Monopoly. In attempting to save in that game, one of the few Master System games with such a feature, the game itself spat out an error message, asking that the "cartridge" be checked.

**Comment by irixxxx** [comment]
SMS support is indeed lacking some polish, rom and sram banking mappers are largely missing. I'm going look into that, but it may take a while.

**Comment by Coolie2** [comment]
> SMS support is indeed lacking some polish, rom and sram banking mappers are largely missing. I'm going look into that, but it may take a while.

Thanks! With how few Master System games seem to use the functionality it's probably not the most important of problems, but I thought I'd mention it. On another note, as I'm now compiling SRAM ROM hacks on my wiki, I noticed that several for the Genesis were created to replace EEPROM saving with SRAM saving, so I was wondering: does PicoDrive support EEPROM saving?

**Comment by irixxxx** [comment]
yes, it does support eeprom saving, in the rom header...

**Comment by irixxxx** [comment]
I did some preliminary work on this. You might have a look at b784d4a5, this might work with the larger amount of available titles with SRAM saves.

**Comment by irixxxx** [comment]
I did some testing and think this is resolved
