### ISSUE TITLE
cmake in infinitive loop

### ISSUE THREAD

**Issue by paloaltonetworksblu** [irixxxx/picodrive#31]
trying to cross build uamqp on mips platform. I added SET(CMAKE_C_COMPILER /opt/mips64-sysroot/usr/bin/mips64-octeon-linux-gnu-gcc) in CMakeLists.txt then ran "cmake ..". It gives the following message and the configure goes on and on:

You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /usr/bin/cc
CMAKE_C_COMPILER= /usr/bin/cc

Not sure what "your cache" means, how do I get around this problem?

**Comment by irixxxx** [comment]
Just throw away the cmake output files. I've googled this for you: https://stackoverflow.com/questions/9680420/looking-for-a-cmake-clean-command-to-clear-up-cmake-output. But how is this related to picodrive?

**Comment by paloaltonetworksblu** [comment]
googled online and found it's a known issue. I followed the workaround to put the compiler settings before the project statement, this issue is resolved.
