### ISSUE TITLE
Allow large SSF2 mapper ROMs loading

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#33]
Some homebrew/demoscene prods abuse SSF2 bank-switching to achieve more than 4MB ROM space. The most extreme case is https://github.com/NatsumiFox/Bad-Apple-MD - 25 megabytes. Works fine on Genesis Plus GX and Blastem, but doesn't seem to run under Picodrive. Would it be possible to implement that?

**Comment by irixxxx** [comment]
fixed with eb3b1f9d
