### ISSUE TITLE
[Master System] Broken PSG emulation in Bad Apple demo

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#34]
I didn't test any other Master System software yet, but I noticed sound is somewhat off in SMS port of a Bad Apple meme demo. Short, high pitched square wave "clicks" can be heard throughout the playback, which shouldn't be there: https://www.youtube.com/watch?v=8IrxK_nT1o8

I assume sth is wrong with ch3/noise channel frequency...

**Comment by irixxxx** [comment]
I did some work on psg audio recently. Is this also the case with current master?

**Comment by irixxxx** [comment]
I did some tests and can hear it...
No, it's not the noise channel - completely disabling that still produces the noise. And it's apparently not an aliasing effect from sampling, since that would change with changing the sampling frequency, which it doesn't. Hmm.

**Comment by irixxxx** [comment]
The resolution for calculating psg sound was on a scanline base. That's apparently not good enough. I changed that to use the same cycle-based clocking used for the ym2616, and the hearable clicks are gone for me.
Could you please check if this solves all of the problems with this?

**Comment by DrUm78** [comment]
That's much worse with your last fix, PSG sound is very distorted (just try Mickey Castle of Illusion on SMS and you'll see). :)

**Comment by freq-mod** [comment]
Click are goen. For sure, it's better now, although for some reason, something seems off (slight distortion, like a very... short clicks on decaying volume levels :eyes:

**Comment by freq-mod** [comment]
Yeah, sound is much dirtier than it should be...

**Comment by freq-mod** [comment]
Also, PCM sample playback is completely broken (Sega chant is 8-bit sonic games). I tried Sonic Blast... and the PSG sound is completely off, like it's lagging/pausing every few ms... weird

**Comment by irixxxx** [comment]
I've changed the way picodrive optimizes sound calculations. That should fix this. Could you please give this another go?

**Comment by freq-mod** [comment]
sure, please wait a moment...

**Comment by freq-mod** [comment]
yes, now it sound good thanks!

**Comment by irixxxx** [comment]
Super. For the record: fixed with 86d6fb9 and 15caa28.

**Comment by DrUm78** [comment]
Works perfectly now, thanks irixxxx!
