### ISSUE TITLE
[Feature Question] Sega Game Gear support?

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#35]
Is it in the scope of this project or planned in some time in the future? Master System support is present, so I got surprised GG isn't here.

**Comment by irixxxx** [comment]
It would require some effort: The sms vdp stuff is very basic and would probably need some rework. Psg audio is stereo in the gg, while picodrive only supports mono for sms. There's probably more...
It's on my list to investigate this (in fact the upscaling code already has some provisions for gg), but I'm not making any promises atm.
I'm en route to 1.99, and the still unfinished show stopper on that list is improving save/load for md, mcd and 32x ;-)
There might also be some improvements for sms (cartridge save/load, more rom mappers, ...) but I'm not sure if I get there in time.
