### ISSUE TITLE
[PocketGo2 v2 / PicoDrive 1.96] Layer priority issue in Mickey Mouse - Castle Of Illusion on Genesis

### ISSUE THREAD

**Issue by Drumaster78** [irixxxx/picodrive#4]
Hardware: PocketGo2 v2
O/S: Rogue FW 1.0.9 for PocketGo2 v2
Software: PicoDrive 1.96
ROM: Mickey Mouse - Castle of Illusion (USA) Genesis version
ROM MD5: 24863151abd5baf28c9386d49ffe3c09

For instance, in 4th stage in 'candy land' sequence or against last boss, I noticed some issues with layer priority.

See the attachments (screenshots and savestates). Note that this issue does not occur with the fast 1.95 OPK I use.

[Mickey.Mouse.-.Castle.of.Illusion.U.zip](https://github.com/notaz/picodrive/files/5151511/Mickey.Mouse.-.Castle.of.Illusion.U.zip)

**Comment by irixxxx** [comment]
Sprite masking was only partially working. Fixed by 8e4ab3c.

**Comment by Drumaster78** [comment]
Fixed verified.
