### ISSUE TITLE
[Game Gear] Start button resets GG Aleste 1 & 2 games instead of launching a game.

### ISSUE THREAD

**Issue by DrUm78** [irixxxx/picodrive#40]
Hardware: FunKey S (SoC V3s ARM Cortex A7-A clocked @ 1.2GHz)
Software: Latest PicoDrive OPK from https://github.com/DrUm78/picodrive-irixxxx/releases.

Start button resets GG Aleste 1 & 2 games instead of launching a game.

Steps to reproduce:
1. Launch GG Aleste 1 or 2 on the FunKey S
2. Press Start button
3. Notice that it resets the game and sends you back to the Sega logo screen

**Comment by irixxxx** [comment]
Picodrive on ARM uses DrZ80, every other version uses Cz80. The latter works fine for both. DrZ80 isn't handling at least some of the undocumented features of the Z80, which shows when running ZEXALL (runs fine but  for 1 test with Cz80). Soo... either someone (who might that be :-/) goes for fixing DrZ80, or I switch over to Cz80 for everything.
This needs some additional scrutiny to asses the perfomance impact of this.

**Comment by freq-mod** [comment]
Can drz80 be disabled for ARM please? I don't see any performance problems on 700 MHz ARM926, although don't have GP2x...

**Comment by irixxxx** [comment]
fixed with d590884. The reason was no DrZ80 but wrong handling of NMI.
