### ISSUE TITLE
[Miyoo/Pocket Go] Glitchy graphics in Sonic Triple Trouble intro

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#43]
I have no idea why does that happen in my self-compiled Miyoo build and not on my x86 PC binary, but still:

![20211103142446_IMG_20211103_140940](https://user-images.githubusercontent.com/32672779/140068360-8e2edce7-81e8-4b74-a216-9286690e48d9.jpg) - as you can see there are some weird blue discolorations around the trees and some blue pixels in random areas. Doesn't happen on x86_64 builds :thinking: 

Maybe some other platforms are affected? Maybe the result of ARM build settings?

**Comment by DrUm78** [comment]
Seems nice for me on the FunKey S with latest code:

![IMG_0131](https://user-images.githubusercontent.com/46139740/140070516-1d8779b6-96a8-4c03-9490-4373bbe7c311.PNG)

**Comment by irixxxx** [comment]
@DrUm78 are you still using cz80? In that case, building with "make use_cz80=1 use_drz80=0" would help.

**Comment by DrUm78** [comment]
@irixxxx Yes, still using CZ80.
I tried again with use_drz80 ?= 1 and that still works well:
![IMG_0127](https://user-images.githubusercontent.com/46139740/140134544-646e7574-3b3c-44c3-850d-528b90531327.PNG).

**Comment by freq-mod** [comment]
It was meant for me I guess. I can try CZ80

**Comment by DrUm78** [comment]
He pinged me. Unless he pinged me mistakenly. :)
But you can try too!

**Comment by freq-mod** [comment]
wtf, still the same bug...

**Comment by freq-mod** [comment]
@irixxxx tried to build it, this time with `make use_cz80=1` only, and
pico/memory.c: In function ‘z80_map_set’:
pico/memory.c:62:5: warning: implicit declaration of function ‘Cz80_Set_Fetch’; did you mean ‘z80_map_set’? [-Wimplicit-function-declaration]
     Cz80_Set_Fetch(&CZ80, start_addr, end_addr, (FPTR)func_or_mh);
     ^~~~~~~~~~~~~~
     z80_map_set
pico/memory.c:62:21: error: ‘CZ80’ undeclared (first use in this function); did you mean ‘drZ80’?
     Cz80_Set_Fetch(&CZ80, start_addr, end_addr, (FPTR)func_or_mh);
                     ^~~~
                     drZ80
pico/memory.c:62:21: note: each undeclared identifier is reported only once for each function it appears in
pico/memory.c:62:50: error: ‘FPTR’ undeclared (first use in this function)
     Cz80_Set_Fetch(&CZ80, start_addr, end_addr, (FPTR)func_or_mh);
                                                  ^~~~
pico/memory.c:62:55: error: expected ‘)’ before ‘func_or_mh’
     Cz80_Set_Fetch(&CZ80, start_addr, end_addr, (FPTR)func_or_mh);
                                                       ^~~~~~~~~~
pico/memory.c: In function ‘z80_mem_setup’:
pico/memory.c:1297:3: warning: implicit declaration of function ‘Cz80_Set_INPort’; did you mean ‘z80_int_assert’? [-Wimplicit-function-declaration]
   Cz80_Set_INPort(&CZ80, z80_md_in);
   ^~~~~~~~~~~~~~~
   z80_int_assert
pico/memory.c:1297:20: error: ‘CZ80’ undeclared (first use in this function); did you mean ‘drZ80’?
   Cz80_Set_INPort(&CZ80, z80_md_in);
                    ^~~~
                    drZ80
pico/memory.c:1298:3: warning: implicit declaration of function ‘Cz80_Set_OUTPort’; did you mean ‘z80_int_assert’? [-Wimplicit-function-declaration]
   Cz80_Set_OUTPort(&CZ80, z80_md_out);
   ^~~~~~~~~~~~~~~~
   z80_int_assert

**Comment by irixxxx** [comment]
You should really use "make use_cz80=1 use_drz80=0", else both are possibly active and confuse each other.

**Comment by irixxxx** [comment]
Hmm, the cpu is arm926. Would you please check that HAVE_ARMv6 is set to 0 in config.mak after configuring?

**Comment by irixxxx** [comment]
I've just cross-checked with qemu-arm. That looks completely normal with both armv5 and armv7 builds. I'll do another check on the caanoo later, that has the same cpu.

**Comment by freq-mod** [comment]
>Would you please check that HAVE_ARMv6 is set to 0 in config.mak after configuring?

Yes, it's set to 0. Should it set it to 1?

**Comment by irixxxx** [comment]
0 is ok since arm926 is armv5, not v6.

I'll probably deactivate drz80, then. cz80 has higher compatibility and doesn't seem to be noticeably slower.

Could you give me the C compiler flags from the make output?

**Comment by freq-mod** [comment]
ummm not sure what do you mean (I'm n00b at coding) but:

`arm-linux-gcc -c -oplatform/linux/emu.o platform/linux/emu.c  -Ipico/cd/libchdr/include  -Ipico/cd/libchdr/deps/lzma-19.00/include -I/home/anon/picodrive -I/opt/miyoo/arm-miyoo-linux-uclibcgnueabi/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result -falign-functions=2 -Wall -g -O3 -DNDEBUG -DSDL_OVERLAY_2X -DSDL_BUFFER_3X -DUSE_LIBCHDR -D_ASM_DRAW_C -D_ASM_MEMORY_C -D_ASM_YM2612_C -D_ASM_MISC_C -D_ASM_CD_MEMORY_C -D_ASM_32X_DRAW -D_ASM_32X_MEMORY_C -D_SVP_DRC -DEMU_C68K -D_USE_DRZ80 -DDRC_SH2 -DUSE_SDL`

**Comment by irixxxx** [comment]
Looks ok so far, but for missing cpu spec. The compiler uses its default which is unknown (well, to me at least). Could you manually add "-mcpu=arm926ej-s" to CFLAGS in config.mak and try again?

**Comment by freq-mod** [comment]
Well, I have bilt it, runs on hardware and such... but it is still glitchy on intro :thinking: 
What's interesting, these blue bars do flicker when the screen is scrolling, and do show up when the screen fades in from black

**Comment by irixxxx** [comment]
Which renderer do you use? (In picodrive menu under display options)?

**Comment by freq-mod** [comment]
16bit accurate, doesn't matter what I change it to though

**Comment by irixxxx** [comment]
What's your configure line?

**Comment by freq-mod** [comment]
just `./configure`, but before that, I'm exporting a few variables as outlined here: https://steward-fu.github.io/website/handheld/miyoo/build_picodrive.htm

`$ export PATH=$PATH:/opt/miyoo/bin` (miyoo toolchain, by steward-fu
`$ export TARGETMACH=arm-linux`
`$ export BUILDMACH=i686-pc-linux-gnu`
`$ export CROSS=arm-linux`
`$ export CC=${CROSS}-gcc`
`$ export LD=${CROSS}-ld`
`$ export AS=${CROSS}-as`
`$ export CXX=${CROSS}-g++`

after, that my configure spits out:
`architecture        arm`
`platform            generic`
`sound drivers        oss alsa sdl`
`C compiler          arm-linux-gcc`
`C compiler flags      -I/opt/miyoo/arm-miyoo-linux-uclibcgnueabi/sysroot/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result`
`libraries           -L/opt/miyoo/arm-miyoo-linux-uclibcgnueabi/sysroot/usr/lib -lSDL -lpthread -lasound -lpng  -lm -lz -ldl`
`linker flags    `    
`libavcodec (mp3)    no`

**Comment by irixxxx** [comment]
Is this happening with other games as well?

**Comment by freq-mod** [comment]
will have to check for any other gg games glitches like that

**Comment by freq-mod** [comment]
-there are similiar blue discolorations/black bars in Ecco:Tides of Time title screen and autoplay demo
-green bars in Mickey Mouse: Legend of Illusion stage 1
-blue discolorations is sonic drift 2, stage 1, on sky

didn't test many games, here are some I managed to catch

**Comment by irixxxx** [comment]
Could you please check if this helps?
[y.txt](https://github.com/irixxxx/picodrive/files/7503098/y.txt)

**Comment by freq-mod** [comment]
I will check, give me a few moments...

**Comment by freq-mod** [comment]
OMFG it finally fixes the problem! Thanks!

**Comment by irixxxx** [comment]
Oh good. Will push this in the evening.
btw qemu-arm apparently ignores data alignment which is why this doesn't happen on my test setup :-/
