### ISSUE TITLE
Provide Miyoo/Bittboy/PocketGo binaries for releases

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#46]
Damn, late for 1.99... still, since I am able to build Picodrive for that target, and it works _near_ flawlessly, binaries for it can be provided for releases too.

**Comment by irixxxx** [comment]
Can do... just point me to the toolchain and hand over the configure/make command.

**Comment by irixxxx** [comment]
(though I normally only support devices I own... do they have some developer program for the hardware?)

**Comment by freq-mod** [comment]
https://steward-fu.github.io/website/handheld/miyoo/build_picodrive.htm contains necessary steps

then, just ./configure, add -mcpu=arm926ej-s to config.mak, and make with use of cz80

**Comment by irixxxx** [comment]
I have decided that I should only give direct support for device I own myself. I don't own a miyoo, hence I won't provide a binary myself - it doesn't make sense as I can't test anything.
I'm open to contributions, though, be it hardware or software. If you have a ready tested build from the v1.99 tag I'm willing to put that up on the release page alongside with contact information in case anyone needs support.

**Comment by freq-mod** [comment]
I see. Well...
[PicoDrive.zip](https://github.com/irixxxx/picodrive/files/7608606/PicoDrive.zip) miyoo binary

**Comment by irixxxx** [comment]
uploaded binary to release page
