### ISSUE TITLE
[YM2612] Ladder effect emulation

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#48]
Separate issue for that. Regarding y.txt patch  https://github.com/irixxxx/picodrive/issues/47#issuecomment-971991586 - I don't know if it's the same thing that got pushed into gh repo (I got error that it does not apply), but once again - I don't hear any ladder effect (maaaaybe some barely audible distortion, but it can also be my headset).

**Comment by irixxxx** [comment]
Just for testing, could you change line 1280 of pico/sound/ym2612.c like this:
```                        *buffer -= (*buffer < 0)*8 << 5;```
and try again? That should double the effect.

**Comment by freq-mod** [comment]
Still nothing, at least nothing that should be ladder effect

**Comment by freq-mod** [comment]
[ladder.mp3.zip](https://github.com/irixxxx/picodrive/files/7563150/ladder.mp3.zip) - just in case; that's how the ladder effect (0:03 onward) should be like in timbre. It's completely missing in x86 Picodrive

**Comment by irixxxx** [comment]
Hmm. I see it doing the same as what's e.g. done in +GX. maybe try disabling the audio filter in the sound settings?

**Comment by freq-mod** [comment]
disabling filter only makes the sound brighter. There is something at the border of being audible, but agian- no idea if it's really here, or it comes from my headset, or background noise :man_shrugging:

**Comment by irixxxx** [comment]
I've moved this back to channel-wise  application. Is this better?
[y.txt](https://github.com/irixxxx/picodrive/files/7564195/y.txt)

**Comment by irixxxx** [comment]
Is the effect too pronounced? I can now hear a very unpleasant and distinct
ringing in quiet parts.

freq-mod ***@***.***> schrieb am Do., 18. Nov. 2021, 15:12:

**Comment by freq-mod** [comment]
Yeah, now there is finally something like ladder effect, but still, it's too strong - it should "last" so long after note release

**Comment by freq-mod** [comment]
@irixxxx yeah - picodrive ladder effect doesn't decay in volume on "duty cycle", while it should.
[ladder.zip](https://github.com/irixxxx/picodrive/files/7565455/ladder.zip)

**Comment by irixxxx** [comment]
Hmm, could you replace ``-4:4`` in pico/sound/ym2612.c line 1240 by ``-2:2`` and check that? [This document](https://docs.google.com/document/d/e/2PACX-1vQ6CEUtCM3U6KKFD3i4lbMaF8muGQ5dez27OcpZOWRP2GgJviklr9rLIQut-LdoGfU4InazlIcbCvlG/pub) suggests that the gap is more like 4 than 8.

**Comment by freq-mod** [comment]
doing this only makes ladder effect less noticeable, ladder then closer to recording i sent earlier

**Comment by irixxxx** [comment]
I can't really see how it's much different from the mame implementation. That adds -2 for negative values and +3 for positive ones. It's also doing this on a per-channel base, which I now think is correct as all channels are routed through one DAC in a TDM like fashion. I'm not that goos at hearing small differences. Is there really a hearable difference?

**Comment by freq-mod** [comment]
I now can see, Picodrive's ladder eff behaviour is same as in GenPlus GX core, where ladder effect is much, much longer. Problem is:
1. https://www.youtube.com/watch?v=bkQ_jRYUWew that's how ladder effect should sound like - get much quieter faster
2. previous ladder effect was better? This one is barely audible, too quiet...

**Comment by irixxxx** [comment]
add this after line 1250 in pico/sound/ym2612.c (before or after the clip call): ```smp &= ~0x1f```

**Comment by irixxxx** [comment]
Actually it's really seems unclear what the hardware is exactly doing. The only real measurement I could find was that from the document, which suggest 3 as the gap. Mame uses 5, +GX uses 7 or 8. Otherwise, code seems very similar to +GX and mame. Now, which of those is most close to the real thing?

**Comment by irixxxx** [comment]
I'm not absolutely sure if I should really trust that source:
```/* YM2612 DAC emulation(not verified) */```

**Comment by freq-mod** [comment]
Nuked OPN2 is almost 100% perfect replication of YM3438's internal logic, but it's YM2612 output is pretty close to real chip.
Anyway, I will try your fix

**Comment by irixxxx** [comment]
Try replacing that ``-2:2``by ``-3:3``. That's basically what that does.

**Comment by freq-mod** [comment]
Much better. In fact, the differences isn't bug, so I don't know if it's worth polishing it even more at this point...

**Comment by irixxxx** [comment]
In fact it's more like ``-3:4``. That's the same +GX uses. It woukd be really strange if it sounds much different. And even more astonishing if there would be much hearable difference to ``-4:4``which I had in the beginning.

**Comment by freq-mod** [comment]
Changed to -3:4, I think it the closest to real hardware so far.  Thanks!

**Comment by irixxxx** [comment]
BTW, out of curiousity, what's you way of testing to compare to real hardware?

**Comment by freq-mod** [comment]
Well, I don't compare to real hardware, only to Nuked OPN2, which is good enough (i.e. produces no audible differences between real hardware and emulation). First I create a simple module in DefleMask tracker, export it to Mega Drive ROM/VGM andplay it in any emulator/VGM player that supports Nuked. Alternatively, I could use a flashcart to play it on real Mega Drive,but I don't have it at the moment.

**Comment by irixxxx** [comment]
Do you know if there are any recordings of this effect are available somewhere? I can only find emulated stuff, but it would be nice to have a real hardware recording for comparison, e.g. something like the moonshine sonata in earthworm jim 2.

**Comment by freq-mod** [comment]
https://www.youtube.com/watch?v=bkQ_jRYUWew 0:27 onward

**Comment by irixxxx** [comment]
I know that one, but ruled that out - they didn't publish the source or binary though, however simple that might be. I can't compare...

**Comment by irixxxx** [comment]
Ah, here: https://www.youtube.com/watch?v=tRkHqw58PPk
By that, the effect seems to be even stronger than what's in picodrive (and Nuked FWIW)?

**Comment by freq-mod** [comment]
There are two FM chips that were uses in Sega Mega Drive: YM2612 (earlier Mega Drives) and YM3438 (somewhat later MDs).
Nuked emulates YM3438, which has much weaker DAC distrortion. Original YM2612 was very noisy
