### ISSUE TITLE
[GKD350H/GKDMINI]v31 system can't run picodrive

### ISSUE THREAD

**Issue by ZOMBIE39** [irixxxx/picodrive#49]
The following content is translated from the translation website.
After some testing, we found that various versions of 1.99, 1.98 and 1.97 including the OD version cannot be run on v31 systems and will flash directly, but the 1.97 version compiled by gameblabla (https://gitlab.com/gameblabla/gameblabla-releases/-/blob/master/opk/350h/PicoDrive_350h.opk) can run, only the v30 version of the system can run the 1.99 version of the OD version of picodrive.
![1](https://user-images.githubusercontent.com/37724369/143261316-f95edebf-51be-4f8f-afd0-f3f8ea576c76.jpg)
By the way, a small suggestion, gkdmini and gkd350h have some hardware differences, no joystick, increased L2R2 button, so gkdmini can have a dedicated version to hide the joystick-related settings options.
PS: A320 can still perfectly run the 1.99 version of picodrive, very good.

**Comment by irixxxx** [comment]
Sorry, I can't help with that. I only support devices I personally own, and I only have a GKD350H with v026. My builds are tested and working on that.
I'm open for contributions and donations though, be it the hardware to be able to give support, or a tested release build from the v1.99 tag.

**Comment by ZOMBIE39** [comment]
I contacted the founder of GKD and he promised to give you a GDKMINI for free, so I hope you can provide me with your address and phone number.

**Comment by irixxxx** [comment]
Would you please contact me via email (it's at the bottom of the repository's README)?

**Comment by ZOMBIE39** [comment]
> Would you please contact me via email (it's at the bottom of the repository's README)?
Have sent an email, if the reply, notify me under this message, I'm not sure if the Chinese domestic Tencent mailbox will block Google mail.

**Comment by irixxxx** [comment]
... and no, I can't download that firmware. From what I gather with my limited Chinese it insists on having an app installed and a registration, which I both don't have.

**Comment by irixxxx** [comment]
I had a look at v031... there are 2 undefined symbols when loading PicoDrive, ``__register_frame_info`` and ``__deregister_frame_info``, which are AFAIK normally defined in libgcc. Well, they are not defined with the v031 firmware.
I can add 2 stub definitions for those functions somewhere as a kludge, but I would rather be interested in an explanation. Even statically linking with a libgcc.a conataining these symbols doesn't seem to help. Some help appreciated here.

**Comment by irixxxx** [comment]
adding ``-u__register_frame_info -u__deregister_frame_info`` does help... is that the correct way to deal with this?

**Comment by irixxxx** [comment]
tested to run with v031-based IUX firmware on GKD350H with a build of b48d7de
