### ISSUE TITLE
[PocketGo2 v2 / PicoDrive 1.96] Freezes in 32X games.

### ISSUE THREAD

**Issue by Drumaster78** [irixxxx/picodrive#5]
Hardware: PocketGo2 v2
O/S: Rogue FW 1.0.9 for PocketGo2 v2
Software: PicoDrive 1.96
ROM: Virtua Racing Deluxe (JAP) 32X version
ROM MD5: 08cae0a96d9ee07001c6e1c247d407c6

At any moment (during a race or in menu) the game may freeze. The emulator keeps working though.
Sometimes you can get a freeze every 10 minutes, sometimes not during 1 hour. Really random.
Sometimes the emulator crashes too but that's very rare. All the OPKs I tested have this issue. I did not get freezes on other 32X games but I play much more to this game than others.

See the attachment (savestates during the freeze):
[virtua_racing_32x_freezes_savestates.zip](https://github.com/irixxxx/picodrive/files/5251583/virtua_racing_32x_freezes_savestates.zip)

**Comment by Drumaster78** [comment]
This happens in Virtua Fighter 32X as well so most likely on every 32X games. Title edited.

**Comment by irixxxx** [comment]
Most probably a cpu synchronisation problem, since the emulator doesn't seem to freeze as a whole. I don't think it happens in every game. I'll have a look in the save games to verify this.

**Comment by irixxxx** [comment]
Do you know if this is happening in the intro as well? That would make it easier for me to reproduce since I wouldn't have to play for an undetermined time.
I would also like to ask how often this is happening to you. Have played the first levels several times, but didn't occur.

**Comment by Drumaster78** [comment]
Yes that happens as well in the intro. Just let it run and you should get it (sometimes after 10 minutes, sometimes after 1 hour). One or two of my saves are from the intro I believe.

**Comment by irixxxx** [comment]
Solved with commits 4153006, 6e8916b
