### ISSUE TITLE
State not fully restored when loading a savestate before the complete game init

### ISSUE THREAD

**Issue by DrUm78** [irixxxx/picodrive#51]
Software: irixxxx's latest code compiled for armv7a7: [1.99-funkey-S](https://github.com/DrUm78/picodrive-irixxxx/releases/tag/v1.99-funkey-s)
Platform: FunKey S

After loading a rom, the user can load a savestate before the game init is complete if they open the menu as soon as they can. Then the game seems to behave fine until you try to reach another stage or sequence through your game, then it displays a black screen and it does not progress any further.
Note that it makes sense as only the savestate content (so the current stage) has been loaded while the whole game init has not been done so the next stage cannot be loaded.
If the user waits for the Sega logo after rom loading then there will be no problem after loading the savestate.
That's maybe not a major issue as waiting for the Sega logo is an easy workaround, but maybe the user should not be allowed to open the menu before the game init is done.
Please note that this bug occurs both on the FunKey S (with its own FunKey menu) and on RG350P too (PD menu) but not on old 1.93 for the FK: I couldn't reproduce it but it seems that we cannot call the menu as fast as with 1.99, that may be the reason, not sure.

**EDIT: The bug first appeared in PicoDrive 1.96 (May 16th 2020) and is not present in 1.95 (November 19th 2019).**

Attachments:
- I attached a savestate for Streets of Rage where you just have to hit once the boss to defeat her to reproduce the bug:
[Streets of Rage (JUE) [!].mds.gz](https://github.com/irixxxx/picodrive/files/7612093/Streets.of.Rage.JUE.mds.gz)
- Footage of the bug (1st part shows that it behaves fine when waiting for Sega logo, 2nd part does not load the following stage as the savestate was loaded before the Sega logo):
https://drive.google.com/file/d/1JtJIeW9AFGd3tdSlqKdXHKpGo0FFsbKs/view?usp=sharing

Workaround:
Wait for the Sega logo to appear then load your savestate.

Steps to reproduce:
1. Select a rom in GMenu2X file selector (you can try Streets of Rage with the attached savestate above)
2. As soon as you have the black screen, open PD menu
3. Load a savestate
4. Play until you complete your current stage
5. You should be stuck on a black screen

**Comment by irixxxx** [comment]
fixed by fda7339b, or at least improved. There still a part of the VDP state not completely saved. That's for next year ;-)
