### ISSUE TITLE
[Genesis] 6 button pad is only detected after entering controls menu

### ISSUE THREAD

**Issue by DrUm78** [irixxxx/picodrive#52]
Software: irixxxx's latest code compiled for armv7a7 (FunKey S) and OPKs for RG350 (1.94 to 1.99).
Platform: FunKey S/RG350P

6 button pad for Genesis is only detected after entering controls menu, even if it was already set for the input device. I first thought it was a bug specific to the FunKey port but then I compiled a raw one from irixxxx's repo (without the FK additions) and tried the RG350 OPK and noticed it.
See the attached video:
https://drive.google.com/file/d/1LEcb6vfaqD99kK3912FHRc4IxdB5DfQF/view?usp=sharing
In this video you can see that Street Fighter II' acts like with a 3 button pad (X button does not work and Start button switches kick and punch) until you get into the "Configure controls" menu, whereas 6 button setting was already set. Entering another menu does not do the trick but only the controls one.
**Please note that the bug has occured since 1.93 version at least (tested all RG350 OPKs and 1.93 on the FK).**
**EDIT: 6 button pad works fine by default on 32X though (X-Men proto), the issue seems to be only for Genesis here.**

Workaround:
Entering "Configure controls" menu fixes the issue for PD ports that can access it.

Steps to reproduce:
1. Set 6 button pad in "Configure controls" menu (on FunKey S if you have one build with menu enabled or RG350 OPK)
2. Exit PicoDrive
3. Launch Street Fighter II' for Genesis
4. Do not enter controls menu and launch a game
5. Notice that you have only 3 button available (punch by default) and Start button allows to switch punch/kick
6. Enter "Configure controls" in PD menu without changing anything
7. Exit this menu
8. 6 button pad is now detected and Start button pauses the game

**Comment by DrUm78** [comment]
Fixed in https://github.com/irixxxx/picodrive/commit/d4d2723f9316a2825b293ce861d2974c18d921f7. Closed. Thanks irixxxx!

**Comment by DrUm78** [comment]
The bug is still happening for per-game .cfg files:
- Set 3 button pad as the default emulator setting
- Set 6 button pad for one specific game
- Exit and launch this game again
- 6 button pad is not automatically detected, the user has to enter the controls menu as a workaround

**Comment by irixxxx** [comment]
fixed by a54716e (hopefully finally!)
