### ISSUE TITLE
[Genesis][ToeJam & Earl] Video hang when letting the attract mode play a long time

### ISSUE THREAD

**Issue by DrUm78** [irixxxx/picodrive#53]
Software: irixxxx's latest code compiled for armv7a7 (FunKey S) and OPKs for RG350 (1.96 to 1.99).
Platform: FunKey S/RG350P
ROM: ToeJam & Earl for Genesis (1st release only as the issue does not occur with Rev A of the game). ROM MD5 must be 0a6af20d9c5b3ec4e23c683f083b92cd to reproduce the bug.

A video hang occurs after about 2h of attract mode when playing the 1st release of the game (not Rev A). Sound continues playing though and the emulator menu can still be called. It can be easily achieved by enabling "Disable frame limiter" and setting FS to the max (16). Please note that this bug appeared in PD 1.96 (still on 1.99 so) and did not happen on 1.94 and 1.95.
Please note that this bug does not occur with other emulators like GX+ or Regen.

Workaround:
Use Rev A ROM instead where the bug does not occur.

Steps to reproduce
1. Launch ToeJam & Earl with PD > 1.95 on the FunKey S or RG350
2. Set "Disable frame limiter" to "ON" and set FS to "16"
3. Let the console play the attract mode for about 5 minutes
4. You should notice the video freeze while the sound is still playing

**Comment by DrUm78** [comment]
Happening on the real hardware too, so PD is very accurate here! Closed.

**Comment by irixxxx** [comment]
Ouf, really! Cool enough.
