### ISSUE TITLE
[GG][DrZ80] Crash during the intro of GG Shinobi

### ISSUE THREAD

**Issue by DrUm78** [irixxxx/picodrive#55]
Software: irixxxx's latest code compiled (f8dba3f63a15f37984f645c2e075eb8c01200b90) for armv7a7 (FunKey S).
Platform: FunKey S
ROM: GG Shinobi for Game Gear. ROM MD5: 8fa7438dec1403f2e9d7b1ca60b29f1a.

A crash occurs with GG Shinobi on arm device with DrZ80 asm core (does not happen with CZ80). Nothing is written into the logs unfortunately. Happens on 1.99 tag as well, so not a very recent regression here.

Workaround:
Skip the intro by pressing Start button.

Steps to reproduce:
1. Compile a binary for arm with Drz80 enabled or use this OPK on the FunKey S:
[picodrive_v1.99_45418cd_funkey-s.zip](https://github.com/irixxxx/picodrive/files/7705778/picodrive_v1.99_45418cd_funkey-s.zip)
2. Launch GG Shinobi game (MD5 indicated above)
3. Watch the intro
4. Notice that it crashes very quickly
5. Now try this OPK (DrZ80 disabled/CZ80 enabled):
[picodrive_v1.99_45418cd_funkey-s.zip](https://github.com/irixxxx/picodrive/files/7706041/picodrive_v1.99_45418cd_funkey-s.zip)
6. Notice that the bug does not occur.

**Comment by irixxxx** [comment]
not reproducible using a generic arm compile running under qemu-arm.

**Comment by DrUm78** [comment]
Same happens on GP2X Wiz with 1.99, it crashes at the same place.

**Comment by irixxxx** [comment]
Also on the Caanoo (that's the same binary as Wiz anyway). Core dump suggest a memory overwrite. Unfortunately no ASAN on those old platforms.

**Comment by irixxxx** [comment]
I managed to run an ASAN instrumented version on qemu-arm. Also discovered that DrZ80 isn't EABI compatible.
Those issues fixed by ac871e1.
