### ISSUE TITLE
[Miyoo/PocketGo] Screen flickers during 32X rendering

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#56]
It's very hard to describe it for me atm, will try my best though:

During stuff like playing Doom, or SEGA logo/opening sequence of Knuckles Chaotix, the screen flickers to black every 1/60th of a second (at least I presume). It doesn't happen during 2D gameplay, though. It might be a matter of triple buffering iirc? (once a miyoo cfw dev mentioned it to me)

EDIT: it also happens on Doom's intermission screen :thinking:

**Comment by irixxxx** [comment]
Probably miyoo-specific. I can't reproduce this with a generic standalone linux version, neither arm nor x86.

**Comment by freq-mod** [comment]
Under Doom, with no frame limit, I get anywhere between 50- 70 fps. Still, the black flickering occurs

**Comment by irixxxx** [comment]
Do you have "Wait for vsync" set in your config file (it shouldn't be available in the UI for linux platforms)?

**Comment by irixxxx** [comment]
There's a potential glitch in the frame synchronisation code. I can't see any difference with this on rg350 and x86 linux, but you could anyway try if this makes any difference on your miyoo:
[y.txt](https://github.com/irixxxx/picodrive/files/7740769/y.txt)

**Comment by freq-mod** [comment]
> Do you have "Wait for vsync" set in your config file (it shouldn't be available in the UI for linux platforms)?

I don't see it at all in confg file, so no i guess

wll try that fix, however

**Comment by freq-mod** [comment]
looks the same

**Comment by irixxxx** [comment]
Try setting the 32x renderer to different values.
Generally 32x rendering is mostly the same as the MD accurate renderer, at least on the platform level. Hence, if accurate rendering works fine for MD and MCD, it should also be fine for 32x.
I presume the miyoo uses the SDL window mode. That's pretty simple on the SDL interface layer - you obtain the pixels pointer from SDL, fill in the pixel data, then call the flip function to display that buffer. Picodrive has logic to make sure that this doesn't happen more than 50/60 times per second.
Frankly, I have no idea what's going on. You could try to write out the buffer stream to a file to check if the buffers are really non-empty when handed to the SDL flip function. That would be in platform/common/plat_sdl.c

**Comment by freq-mod** [comment]
Setting it to faster in 32x rendering options fixed the issue. Thanks nevertheless

**Comment by irixxxx** [comment]
Really strange. Timing problem? In that case I think it might well occur again somewhere else :-/
