### ISSUE TITLE
[PocketGo2 v2 / PicoDrive 1.96] 'Disable frame limiter' option does not work.

### ISSUE THREAD

**Issue by Drumaster78** [irixxxx/picodrive#6]
Hardware: PocketGo2 v2
O/S: Rogue FW 1.0.9 for PocketGo2 v2
Software: PicoDrive 1.96

'Disable frame limiter' in Advanced options simply does nothing when it's activated, the emulator is still capped at 60 fps. whereas Fast forward works.

**Comment by irixxxx** [comment]
Hmm, it works fine using SDL window rendering under Ubuntu, which uses the same code.

**Comment by Drumaster78** [comment]
Works fine with FS>0. Please note that it does not really remove frame limit but speeds up the game up instead (still displays 60 fps), but that works the same way on devices like GP2X Wiz so I guess that's intended. Bug closed.

**Comment by irixxxx** [comment]
for documenting purposes, that's the Frameskip option.
