### ISSUE TITLE
Old performance degradation in Mega Drive and Mega CD

### ISSUE THREAD

**Issue by asoderq** [irixxxx/picodrive#60]
Hi Irixxxx,

a long time a go, like 20 months, I discovered a performance degradation in picodrive. This affects Mega Drive and Mega CD at least. It will only be detectable on lower end hardware, I discovered it on a jz4760 (clocked at 600Mhz) running RetroFW. It is related to this commit or later:
https://github.com/irixxxx/picodrive/commit/0f3703fd9809452251321364ef788ff7ab156392
But not later than 5th of May 2020, as that was when I discovered it with the current build at that time. Checking out the commit before, meaning this one: 
https://github.com/irixxxx/picodrive/commit/4bb8111a050ad97e24a9ddb41f65a85891a30048
has the original performance.  

The games where it is noticeable are:
Panorama Cotton (J) (Mega Drive) (Actually a very good shooter, and probably the most demanding Mega Drive game to emulate)
Batman Returns (U) (Mega CD) (A very demanding Mega CD game to emulate)

With the old build Panorama Cotton runs full speed at 60FPS on jz4760 (600MHz, with RetroFW). With the new build it goes down into the 50s FPS-wise. Batman Returns doesn't run at 60FPS even with the old version, but sees a degradation in FPS with the newer build.

This has led the RetroFW community (well, at least me) to require two builds of Picodrive, the old one that doesn't show this performance degradation and the latest one. Do you think it is possible go back to the original performance? Or was this related to a fix in accuracy that has other benefits, which makes it undesirable to go back?

Let me know if I can provide you with more information that may be of help.

**Comment by irixxxx** [comment]
Hmm, that sounds like bisecting would be a good idea.

**Comment by irixxxx** [comment]
4bb8111 is before the VDP FIFO redisign, which improved the emulation accuracy of the VDP data transfer. If that's the case it must have happened before 3c6da92. Could you check if this revision is already affected?

**Comment by asoderq** [comment]
It took me a while to get the toolchain ready and patch the build system to build for retrofw.
672b29e has very strange behavior, the FPS counter alternates between 30 and something in the 50s, very strange. Never seen this behavior before, not sure what to make of it.

**Comment by irixxxx** [comment]
After some finagling I have now quite some indications that this comes from the renewed VDP FIFO. I suspected so anyway, which is why I started a rework a while ago, but it isn't ready yet. I've taken up the rework code to get it into a basically working state. I'll notify you if I have something for a first test.

**Comment by irixxxx** [comment]
I've pushed some changes which might improve performance a bit. If you would please make a version from my current master and check?

**Comment by asoderq** [comment]
I have tested and performance have improved:
Panorama Cotton is now 59-60 FPS all the time in the first section of the game. This had dips to ~55 FPS before.
Batman Returns still perform worse with an average at perhaps 35-40 FPS. The old version get perhaps 40-45 FPS in average. This all tested on an RG300 clocked at 600MHz.
I'd say it's pretty good now, the whole Mega Drive library should be full speed. Batman returns is not really a game that I play other than when benchmarking. So I am happy and will remove the old version from my device.
In case you want any more performance testing I am available, if you consider this topic closed that is of course OK!
I appreciate your effort :)

**Comment by asoderq** [comment]
Just an idea, we could enable LTO for the RetroFW build (and potentially other low power devices). I remember you saying that to do that you had to change something that reduced performance for 32x. But honestly 32X is out of reach for these devices anyway. You mentioned it here: https://github.com/irixxxx/picodrive/issues/36#issuecomment-932884886

So maybe you could have an IFDEF on that, so that you can LTO for low power devices. This would would probably be helpful for the Sega CD performance

**Comment by irixxxx** [comment]
LTO would probably be a good idea with a recent enough version of gcc, 9+ I'd say.
As for 32X, my 800 MHz caanoo can do a lot of 2D titles in full speed (some only with frame drops), but the 3D games are too heavy for it. So, you might want to try how well e.g. Tempo or Pitfall run on your device.

**Comment by asoderq** [comment]
When I clock my rg300 to 672MHz (max it can do). I get:
10 FPS in Virtua Racing Deluxe
Knuckles Chaotix around 10-20 FPS depending on how much is going on.
Both have stuttering sound, and slowdowns. This is for me not really playable.
But perhaps the performance gain from LTO is greater than what we lose?

Anyway I am running 2.3rc2 release of RetroFW.
Images: https://drive.google.com/drive/folders/1fkfWDHvW5yfVHXQPaVvgV2RBPmUSNK_Z
Buildroot: https://github.com/Poligraf/buildroot/tree/2021.11.x
This is where I got my toolchain, which has gcc 11.2.0

**Comment by irixxxx** [comment]
I did my 1st experiments with LTO using gcc 4.7, and that was actually detrimental. However, things have improved considerably between gcc5 and 8, so it's definitely worth a try.

**Comment by asoderq** [comment]
What is it exactly i have to remove in this file to enable LTO?
https://github.com/irixxxx/picodrive/blob/master/cpu/sh2/compiler.h

**Comment by asoderq** [comment]
When just removing these two lines:
https://github.com/irixxxx/picodrive/blob/master/Makefile#L359
I get the following error when trying to LTO:
```
pico/32x/memory.c:46:1: error: global register variable follows a function definition
   46 | DRC_DECLARE_SR;
      | ^
lto-wrapper: fatal error: /home/alexander/git/retrofw/buildroot/output/host/bin/mipsel-RetroFW-linux-uclibc-gcc.br_real returned 1 exit status
compilation terminated.
/home/alexander/git/retrofw/buildroot/output/host/lib/gcc/mipsel-RetroFW-linux-uclibc/11.2.0/../../../../mipsel-RetroFW-linux-uclibc/bin/ld: error: lto-wrapper failed
```

**Comment by irixxxx** [comment]
You are on mips... look for "s6", or "defined mips". comment the lines for DRC_SR_REG and DRC_REG_LL.

**Comment by irixxxx** [comment]
FYI, my retrofw toolchain compiles the master branch with -flto... that's a gcc 7.

**Comment by asoderq** [comment]
> FYI, my retrofw toolchain compiles the master branch with -flto... that's a gcc 7.

Hah, odd! Yeah, my 11.2 also compiles master with -flto without the modifications. When I tried to compile the libretro core a while back it wasn't possible with -flto, but that was for aarch64 in a qemu-chroot env. I got this error mentioned here:
https://github.com/irixxxx/picodrive/issues/36#issue-1014193932
Remember?

Anyway thanks for clearing that, meanwhile I did have time to test the LTO'd version with the modifications. Result was slightly slower 32x and slightly faster Sega CD. But since it does compile without changing those things I guess I don't have to make that compromise.

**Comment by asoderq** [comment]
By the way when I build I do like this:
```
CROSS_COMPILE=$TC/bin/mipsel-RetroFW-linux-uclibc- CFLAGS="-flto -I $TC/include -I $TC/include/SDL -Wno-unused-result" LDFLAGS="-flto --sysroot $TC/mipsel-RetroFW-linux-uclibc/sysroot" ./configure --platform=retrofw
make -j4
```

**Comment by irixxxx** [comment]
just make sure all -m options from CFLAGS are also in LDFLAGS... or modifiy the $(LD) link line in Makefile, see above...

**Comment by asoderq** [comment]
I don't know what you mean by -m options. I add -flto to both CFLAGS and LDFLAGS.

By the way do you have any insight into the newer musashi releases? Are they slower?
I see that Picodrive has 3.3. while upstream is at version 4.10.

I was playing with the idea of transplanting in 4.10 in Picodrive and test it...

**Comment by irixxxx** [comment]
e.g. "-march=mips32r2", "-mabicalls", "-msoft-float", "-mfpu=...". Some of those are added by the configure script, so you mnight want to check the resulting config.mak file and manually add all -m... (and probably -f... too) found in CFLAGS also to LDFLAGS.

For LTO, the compiler stores an internal representation of the code and doesn't call the assembler. That's now done by the linker... the assembler needs those flags, else it won't work. IIRC all optimization options should also be passed to the linker, but I might be wrong on that one.

**Comment by irixxxx** [comment]
I can't say much about musashi. I only use it as a verification for fame, as I believe it is slower than the fame implementation in picodrive. I have never measured it though.

**Comment by asoderq** [comment]
> I can't say much about musashi. I only use it as a verification for fame, as I believe it is slower than the fame implementation in picodrive. I have never measured it though.

Ohh, my misunderstanding. I thought musashi was used for the mips build. I see now it is not used for any build.

**Comment by asoderq** [comment]
I will do some more experiments with compiler flags and also stripping the binary during the evenings this week. If you don't mind we can leave the issue open so I can report the results here.

**Comment by asoderq** [comment]
In my tests with Batman Returns these two flags seems to generate slightly worse performance:
```
 -finline-limit=42 -fno-unroll-loops
 ```

**Comment by irixxxx** [comment]
These 2 options generally produce smaller code. I measured performance on my Caanoo and found that performance was better when limiting the code size.
I-cache size on Caanoo is 16KB, which AFAIK is the same in the JZ4760, hence I would expect similar behaviour. To get a better overview, would you please try to increase the inline limit to 60 and report back?

**Comment by asoderq** [comment]
I would need a way to measure more exactly, this is just base on my observation of the FPS counter while playing the first level.
I feels tricky, and it is impossible to do deterministically but it can definitely be done more exact than my current method. I would need some sort of average frame rate during the first level. So an option to have a running average of the frame rate with a reset functionality would be required. That itself would of course impact performance but only when turned on, so it would make game slower but it would make it possible to compare.

Also maybe relevant is the RAM. I think the RG300 has DDR2 and know it was overclocked in RetroFW 2.3. But I don't at which frequency it is running at, nor the byte width of the interface itself. I might poke around to see if I can figure that out.

**Comment by asoderq** [comment]
I can't figure out the frequency. But it is DDR2, and it was actually not overclocked but the CAS Latency was lowered from 6 to 3. Which I think should decrease the cost of cache misses.

**Comment by irixxxx** [comment]
L1 cache misses are rather expensive, especially if you run into cache thrashing. That's why I limited code expansion by the compiler a bit. The actual options for this were determined by experiment, so they might not be perfectly chosen.

**Comment by asoderq** [comment]
There doesn't seem to be an option of controlling how much gcc unroll loops. I am thinking that by halving the iterations for each loop would bring the biggest performance improvement, and least code expansion.

**Comment by irixxxx** [comment]
Hmm, I seem to remember it's done via the --param option.

**Comment by asoderq** [comment]
Yeah, you are right we need to keep the binary small. And since I can't measure performance in any good way, I have started looking at binary size. Where `-flto` helps of course, but I also found that `-fipa-pta` lowers the code size and has better performance.

It is actually surprising how much the performance improved with these two flags. I am testing Batman Returns at 672MHz and with the old old version it runs at 59-60FPS all the time. Without any more flags (other than what you specified) with current code base i get dips down to 40 FPS (maybe even down in 30s sometimes). With these two flags additional it is a lot of the time 59-60FPS, sometimes dips down to mid 50s and have just once I have seen 51FPS.

I have made a list of optimization flags which I will see how they affect binary size, and if they lower it I do manual test with games. I will report back my findings of course.

**Comment by irixxxx** [comment]
Be careful with this. Although -Os makes the code much smaller, it normally gets noticeably slower. So, a good balance must be found.

**Comment by asoderq** [comment]
I think this is it, no other flags had any significant impact to binary size. I tried unrolling loops 1 time, I tried changing inline limit up and down. Everything was worse. At least I gained something with `-flto` and `-fipa-pta` which I think the RetroFW binary should be built with when the next release is coming.

**Comment by irixxxx** [comment]
Could you be more specific? Which other options are set, I guess at least ``-O3``?

**Comment by asoderq** [comment]
Sorry I realized now that I have tested without this whole line of flags: https://github.com/irixxxx/picodrive/blob/master/Makefile#L56
Are you sure about those options giving 20% performance improvement?
I found that many of these flags didn't change the code size at all, but I remember that -fno-guess-branch-probability did change it. Hmm, OK I will test with these flags more thoroughly tomorrow.

**Comment by asoderq** [comment]
This whole line of options have negative performance impact for me:
https://github.com/irixxxx/picodrive/blob/master/Makefile#L56

For RetroFW: 1. Remove this line (56) 2. Append `-flto -fipa-pta` to CFLAGS 3. Append CFLAGS to LDFLAGS.

I dumped the idea of profiling because Batman Returns is the only game that has bad performance, and it is game that uses the CD's sprite-scaling and -rotation feature. And it is probably stupid to profile on this rarer code path. Another game which also uses these features, Soul Star, runs fine. Anyhow with these new compiler flags we are almost back at the performance of that old version. But it is definitely good enough for me to forget about it an remove that opk from rg300, it was just so annoying to always have to picodrives installed.

**Comment by irixxxx** [comment]
hmm, intersting. I came up with this after extensive experiments on the Caanoo, which has an ARM9 cpu. However, it uses the very old gcc 4, and since those experiments the code base has changed considerably. I guess I need to do some experiments of my own to recheck this ;-)

**Comment by asoderq** [comment]
Please do, and probably best to build the RetroFW binary with latest toolchain that I have used now.
This seems to be the new location of the RetroFW buildroot in case you want to build the latest toolchain for yourself:
https://github.com/retrofw/buildroot-retrofw-2.3/tree/2021.11.x

 In case you have problem with that toolchain I can always build it.

**Comment by asoderq** [comment]
Thanks for the effort on trying to improve this and all advice. I am glad we managed to improve the performance as much as we did. I am considering this issue done and closing it.

**Comment by irixxxx** [comment]
@asoderq as part of the preparations for 2.00 I changed the optimisation options in the Makefile. Could you possibly check the performance with the new set, please?

**Comment by asoderq** [comment]
Ohh might be tough for me to test any time soon. But as long as you have -fipa-pta it should be better.

**Comment by irixxxx** [comment]
Yes. If the gcc version supports it, -fipa-pta is used.
