### ISSUE TITLE
Unable to build fresh master

### ISSUE THREAD

**Issue by freq-mod** [irixxxx/picodrive#62]
platform/common/emu.c: In function ‘emu_update_input’:
platform/common/emu.c:1183:26: error: ‘IN_BINDTYPE_PLAYER34’ undeclared (first use in this function); did you mean ‘IN_BINDTYPE_PLAYER12’?
  pl_actions[2] = actions[IN_BINDTYPE_PLAYER34];
                          ^~~~~~~~~~~~~~~~~~~~

**Comment by irixxxx** [comment]
It's defined in the libpicofe submodule and that is correctly referenced in master. Have you updated your submodules?

**Comment by freq-mod** [comment]
i thought i did, but turns out not. Now its fine, thanks
