### ISSUE TITLE
[retrofw] emulator hotkey config not working

### ISSUE THREAD

**Issue by smilerliu** [irixxxx/picodrive#63]
Steps to reproduce:

1. Change pad type from 3 buttons to 6 buttons for device 1
2. Map L, X and R to the buttons X, Y and Z.
3. Find out that X is still mapped to fast forward.
4. Go to the emulator hotkeys screen and see nothing there, and can't reconfigure the hot keys.
5.  Open the picodrive config file with a text editor and see that L, X and R are each mapped to multiple functions.
6.  Manually remove the extra mappings from the config file, and everything works as intended (that is, L, X and R are mapped to X, Y and Z).

I'm using asoderq's fork of 1.99 on retrofw 2.3 rc2 on an rg300.

**Comment by irixxxx** [comment]
Here's a patch to the libpicofe submodule to try:
[y.txt](https://github.com/irixxxx/picodrive/files/8107658/y.txt)

**Comment by smilerliu** [comment]
With this patch, I can clear and set emulator hot keys, but nothing is ever shown in the emulator hot key screen.

**Comment by irixxxx** [comment]
fixed in libpicofe with commit 49190405

**Comment by smilerliu** [comment]
Is it possible to make the key bindings show in the emulator hotkey screen?

**Comment by irixxxx** [comment]
yes, they do so.
