### ISSUE TITLE
[retrofw] screen flashing when entering/exiting emulator menu

### ISSUE THREAD

**Issue by smilerliu** [irixxxx/picodrive#64]
When I switch between the game and the emulator menu, the screen will flash. For instance, when I exit the menu and go back to the game, the screen first shows the game, and then back to the menu, and then back to the game again, all in a quick sequence. The expected behavior is that I see the game screen right away without the quick flashing of the menu screen.

I'm using asoderq's fork of 1.99 on an rg300. I can observe the same problem with both retrofw 2.2 (the stable version) and retrofw 2.3 rc2.

**Comment by irixxxx** [comment]
platform specific to RetroFW 2.3, since the code is the same for all platforms using SDL, and AFAIK it works correctly on RG350, GK350H and Linux, and AFAIK it also works on RetroFW 2.2.
I can't currently do much about it since I have only a RetroFW2.2 device. Anyone?

**Comment by asoderq** [comment]
smilerliu did say that it also occurs on RetroFW 2.2. 

(Also I didn't know you had a retrofw device :) )

**Comment by smilerliu** [comment]
Here is a video demonstrating the problem. It's for 2.3, but 2.2 behaves the same. https://drive.google.com/file/d/1pgpFV5hHd_UZg2gIpOGuiTvqkWeZ8zmW/view?usp=drivesdk

**Comment by irixxxx** [comment]
Hmm, after studying the code I think it might be possible that there's a bug in the SDL library. Where are the sources, please?

**Comment by smilerliu** [comment]
What sources do you need?

BTW: FYI, this older version of picodrive doesn't have this problem: https://github.com/retrofw/picodrive/releases/tag/2020-05-16

**Comment by asoderq** [comment]
Here is RetroFW SDL package in buildroot, it consists of the latest stable release 1.2.15 and 16 patches.
https://github.com/retrofw/buildroot-retrofw-2.3/tree/2021.11.x/package/sdl

**Comment by irixxxx** [comment]
thx, I'll investigate this.
Is any upscaling option activated? If so, hard or software?

**Comment by smilerliu** [comment]
All scaling is turned off.

**Comment by irixxxx** [comment]
Could you please compile without triple buffer support and check again? You can do this by removing ``-DSDL_BUFFER_3X`` from the CFLAGS in Makefile.

**Comment by irixxxx** [comment]
Sorry, wrong click...

**Comment by smilerliu** [comment]
Entering the menu sometimes has no flashing, but exiting the menu still always has the flashing. Video to demonstrate the problems: https://drive.google.com/file/d/1FDBr3-bt_1XAyAzVcT-sskB8rN7XXIVU/view?usp=drivesdk

**Comment by smilerliu** [comment]
This is will all scaling turned off.

**Comment by irixxxx** [comment]
Hopefully fixed by f8aaa20
