### ISSUE TITLE
[PocketGo2 v2 / PicoDrive 1.96] Major performance drop in 32X games

### ISSUE THREAD

**Issue by Drumaster78** [irixxxx/picodrive#7]
Hardware: PocketGo2 v2
O/S: Rogue FW 1.0.9 for PocketGo2 v2
Software: PicoDrive 1.96

As discussed on Dingoonity, I noticed a huge performance drop with 32X games in the last 1.95 and 1.96 OPKs compared to how it ran with OPK built in November 30th (attached to this ticket).
The settings are the same through the different OPKs I tested. Note that the performance drop is also occurring with Genesis games but not very noticeable as it still runs at 60 fps. It's noticeable when using 'Fast forward' feature where the performance is way higher with the fast OPK (60/540 against 30/270).

Here is the video footage showing (in the 1st part) the game running fullspeed with the fast OPK and then, in the 2nd part, running slower (game and sound) with 1.96 OPK:
https://drive.google.com/file/d/13b03Z6mM6RBMXP_0NKnLobXvfPLlKGYS/view?usp=sharing

I also attached the zipped fast OPK for comparison:
[picodrive_gcw0.zip](https://github.com/irixxxx/picodrive/files/5251640/picodrive_gcw0.zip)

**Comment by irixxxx** [comment]
Apparently this hits only jz47xx MIPS-based devices with opendingux OS. I can reproduce this neither under linux nor on a caanoo.

@gameblabla discovered this to be related to SDL double buffering. Enabling triple buffering seems to solve the issue.
Another idea would be to use OpenGL|ES for the screen rendering. However, this has to wait until I can get my hands on the hardware.

**Comment by irixxxx** [comment]
Verified that by enabling triple buffering in libpicofe issue goes away. Misplaced here since libpicofe has its own repo. I'm going to PR this to @notaz RSN.
