### ISSUE TITLE
Feature request: Linux OpenGL, or fully scalable SDL, support

### ISSUE THREAD

**Issue by noabody** [irixxxx/picodrive#70]
Would you consider supporting Linux x86_64 as a build platform with the OpenGL back-end or a fully scalable SDL implementation?  

The GUI works well until the scaled aspect ratio becomes greater than 4:3?  At that point the menu tilts.

Here are the patches I've been using to force OpenGL.  Please keep in mind that I kludged this together because I'm NOT a programmer.  I really don't know how best to implement this.

The last patch is to use an SDL Hat switch on the joystick.  notaz had some concerns but I don't really know if that is an issue. See [3](https://github.com/notaz/libpicofe/pull/3)
```
diff a/picodrive/Makefile b/picodrive/Makefile
index 2903a68..bad1aa5 100644
--- a/picodrive/Makefile	1969-12-31 17:00:00.000000000 -0700
+++ b/picodrive/Makefile	1969-12-31 17:00:00.000000000 -0700
@@ -164,7 +164,8 @@ OBJS += platform/libpicofe/gl_platform.o
 USE_FRONTEND = 1
 endif
 ifeq "$(PLATFORM)" "generic"
-CFLAGS += -DSDL_OVERLAY_2X -DSDL_BUFFER_3X
+CFLAGS += -DHAVE_GLES
+LDFLAGS += -ldl -lpthread -lGL -lEGL
 OBJS += platform/linux/emu.o platform/linux/blit.o # FIXME
 ifeq "$(use_inputmap)" "1"
 OBJS += platform/common/plat_sdl.o platform/opendingux/inputmap.o
@@ -173,6 +174,7 @@ OBJS += platform/common/plat_sdl.o platform/common/inputmap_kbd.o
 endif
 OBJS += platform/libpicofe/plat_sdl.o platform/libpicofe/in_sdl.o
 OBJS += platform/libpicofe/plat_dummy.o platform/libpicofe/linux/plat.o
+OBJS += platform/libpicofe/gl.o platform/libpicofe/gl_platform.o
 USE_FRONTEND = 1
 endif
 ifeq "$(PLATFORM)" "pandora"
```
```
diff a/picodrive/platform/libpicofe/gl.c b/picodrive/platform/libpicofe/gl.c
--- a/picodrive/platform/libpicofe/gl.c	1969-12-31 17:00:00.000000000 -0700
+++ b/picodrive/platform/libpicofe/gl.c	1969-12-31 17:00:00.000000000 -0700
@@ -2,7 +2,11 @@
 #include <stdlib.h>
 
 #include <EGL/egl.h>
-#include <GLES/gl.h>
+#if defined(__arm__)
+  #include <GLES/gl.h>
+#else
+  #include <GL/gl.h>
+#endif
 #include "gl_platform.h"
 #include "gl.h"
 
```
```
diff a/picodrive/platform/libpicofe/gl_platform.c b/picodrive/platform/libpicofe/gl_platform.c
--- a/picodrive/platform/libpicofe/gl_platform.c	1969-12-31 17:00:00.000000000 -0700
+++ b/picodrive/platform/libpicofe/gl_platform.c	1969-12-31 17:00:00.000000000 -0700
@@ -1,7 +1,11 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include <EGL/egl.h>
-#include <GLES/gl.h>
+#if defined(__arm__)
+  #include <GLES/gl.h>
+#else
+  #include <GL/gl.h>
+#endif
 
 #include "gl.h"
 #include "gl_platform.h"

```
```
diff a/picodrive/platform/libpicofe/in_sdl.c  b/picodrive/platform/libpicofe/in_sdl.c
--- a/picodrive/platform/libpicofe/in_sdl.c	1969-12-31 17:00:00.000000000 -0700
+++ b/picodrive/platform/libpicofe/in_sdl.c	1969-12-31 17:00:00.000000000 -0700
@@ -300,6 +300,34 @@
 		}
 		break;
 
+	case SDL_JOYHATMOTION:
+		if (event->jhat.which != state->joy_id)
+			return -2;
+		if (event->jhat.value == SDL_HAT_CENTERED) {
+			kc = state->axis_keydown[event->jhat.hat];
+			state->axis_keydown[event->jhat.hat] = 0;
+			ret = 1;
+		}
+		else if (event->jhat.value & SDL_HAT_UP || event->jhat.value & SDL_HAT_LEFT) {
+			kc = state->axis_keydown[event->jhat.hat];
+			if (kc)
+				update_keystate(state->keystate, kc, 0);
+			kc = (event->jhat.value & SDL_HAT_UP) ? SDLK_UP : SDLK_LEFT;
+			state->axis_keydown[event->jhat.hat] = kc;
+			down = 1;
+			ret = 1;
+		}
+		else if (event->jhat.value & SDL_HAT_DOWN || event->jhat.value & SDL_HAT_RIGHT) {
+			kc = state->axis_keydown[event->jhat.hat];
+			if (kc)
+				update_keystate(state->keystate, kc, 0);
+			kc = (event->jhat.value & SDL_HAT_DOWN) ? SDLK_DOWN : SDLK_RIGHT;
+			state->axis_keydown[event->jhat.hat] = kc;
+			down = 1;
+			ret = 1;
+		}
+		break;
+
 	case SDL_JOYBUTTONDOWN:
 	case SDL_JOYBUTTONUP:
 		if (event->jbutton.which != state->joy_id)
```

**Comment by noabody** [comment]
![picodrive](https://user-images.githubusercontent.com/29848078/166291548-f92246c6-629a-481e-bdff-70f75c725783.png)

**Comment by irixxxx** [comment]
What exactly have you done to get this display? I can't reproduce this neither with SDL window not with overlay.

The GL support is unfortunately quite hardcoded for Raspi. I have already tried to get this running on a more general base, but ultimately decided it would need SDL2 to do this in a more portable way. That however is some work for dark windy fall days ;-)

**Comment by noabody** [comment]
I hear you on the SDL2.  Let me elaborate on my situation.  I'm building picodrive on Arch-like Manjaro 21.2.6 x86_64 Linux, not on an Arm based micro platform.  I have been able to package it using my personal, an someone unorthodox, [patch](https://raw.githubusercontent.com/noabody/unibuild/master/data/arch/picodrive.patch).

I can build picodrive for Linux x86_64 without the patch but it is forced into an SDL 2x window because the Makefile considers my platform to be _generic_.  I can modify generic to use opengl as shown in the patches but we really need a separate platform.  Maybe the code would look something like this?
```
ifeq ("$(PLATFORM)",$(filter "$(PLATFORM)","__linux__"))
CFLAGS += -DHAVE_GLES
LDFLAGS += -ldl -lpthread -lGL -lEGL
OBJS += platform/linux/emu.o platform/linux/blit.o # FIXME
OBJS += platform/common/plat_sdl.o platform/common/inputmap_kbd.o
OBJS += platform/libpicofe/plat_sdl.o platform/libpicofe/in_sdl.o
OBJS += platform/libpicofe/plat_dummy.o platform/libpicofe/linux/plat.o
OBJS += platform/libpicofe/gl.o platform/libpicofe/gl_platform.o
USE_FRONTEND = 1
endif
```
Anyway, once I build it for Arch Linux and opengl, Picodrive works quite well.  Without the patch, the GUI is not resizable and it isn't useful.  My interest in the project is as a tinkerer.  That's who [noabody](https://noabody.wordpress.com/) is.

**Comment by irixxxx** [comment]
I'll see if I can find that old patch. It had all the basics covered, but there were some problems left (can't remember which ones though).

**Comment by irixxxx** [comment]
Here's my old patch. It's ugly, and I gave up on it because I could control the redraw stuff properly. The picodrive architecture just wasn't designed with supporting a proper window system in mind.
[gl.txt](https://github.com/irixxxx/picodrive/files/8673318/y.txt)

**Comment by irixxxx** [comment]
I was compiling this code under x86_64 xubuntu. I just had to install libgles1. It's also available under ubuntu armv8, hence I think it's rather standard fare. Is this not available on your distro?

**Comment by noabody** [comment]
Regrettably, Arch Linux does not have a package with "include/GLES/gl.h".  The file gl.h only exists in location "include/GL/gl.h" as part of package [libglvnd](https://archlinux.org/packages/extra/x86_64/libglvnd/).

I wasn't aware of that so it is an issue for me, as a packager of a sort (```perl -pi -e 's|(GL)ES(/gl\.h)|\1\2|gi' platform/libpicofe/gl{,_platform}.c```).  Your patch compiled after I fixed the include location, set ```LDFLAGS += -lGL -lEGL```, and ```./configure --with-sdl-gles=yes``` then make.

I can resize the window but it's contents are blank and this is printed in the command console: ```GL error: glTexSubImage2D 501```

If you want to have me test out code, I'd be happy to.  As it is, I definitely think this is a "rainy day" project and Arch Linux is an anomaly even for x86_64.

**Comment by irixxxx** [comment]
Please try again with current master. It works on current Xubuntu, but I guess there's more checking for specific libraries needed. I'd welcome hints which libs I need to check for in configure.

**Comment by noabody** [comment]
Thanks for your hard work!  I'm sure Xubuntu is fine.  Arch Linux is always madly updating to the latest thing.  They broke the EGL code with an update in July so I only get an error in the console ```eglSwapBuffers failed 300d```.  I looked into it a bit and the older libraries in Ubuntu variants work.

I gave up on it thinking SDL is probably the way to go but, of course, it segfaults.  gdb has this output:
```
plat_sdl: overlay: fmt 59565955, planes: 1, pitch: 1280, hw: 1

Thread 1 "PicoDrive" received signal SIGSEGV, Segmentation fault.
0x000055555556858e in plat_sdl_change_video_mode (w=640, h=480, force=force@entry=1) at platform/libpicofe/plat_sdl.c:110
110	      if ((long)plat_sdl_overlay->pixels[0] & 3)
```
Basically, the code base in Picodrive is just a bit out of reach of newer Arch distributions but it works fine on the intended targets.

**Comment by irixxxx** [comment]
AFAIK the GLES code in Picodrive was specifically designed for Pi 1 and 2. SDL 1 isn't supporting GL directly, hence it's basically a kludge. Lucky me that it worked more or less out of the box under Xubuntu.
The crash you observe is in the SDL overlay code. Maybe it misses locking the surface before accessing the pixels in the surface. Try adding ``SDL_LockYUVOverlay(plat_sdl_overlay);``in the line before the if, and ``SDL_UnlockYUVOverlay(plat_sdl_overlay);``in the line after plat_sdl_overlay_clear() and see if that works better for you.

**Comment by noabody** [comment]
Yeah that fixed it right up.  I might fool around with the EGL code a little - which means I might track down similar examples, based on the error, and see if I can apply their fixes to this code base ;).  It might be a surface locking issue also affecting the eglSwapBuffers.

That however is related to newer libraries deciding that features should be implemented in a slightly different way - in the name of progress :package: 

We should probably close this feature request.  Short of a re-implementation to future proof some of the GL code, it is doing exactly what it's supposed to do.

**Comment by noabody** [comment]
After some research, I'm thinking Arch's Mesa EGL gets fouled up by having multiple platforms X11/DRM/Wayland.  Reading [c - EGLDisplay on GBM](https://stackoverflow.com/questions/20816844/egldisplay-on-gbm) suggests a different mechanism for interacting with these than what is used in gl.c.

**Comment by irixxxx** [comment]
I did my best to improve handling of redraw events, but with the current design of input handling this is limited. It should basically work, but there are still some situation where window redrawing is done incorrectly after resizing. libpicofe and picodrive input handling would need a redesign to handle this correctly.

However, this has improved window resizing considerably.
Last commit for this was 54f74b8. Please check this for sdl window and sdl overlay modes.

**Comment by noabody** [comment]
Strictly speaking, ```Change Options > Display Options > Video Output Mode > SDL``` doesn't scale but ```Video Overlay/[2x]``` both seem to work fine and are exactly what I was looking for.  

Performance seems good in full-size window on monitor set to 1920x1080.

Excellent work!

**Comment by irixxxx** [comment]
SDL window mode is more for the lot of linux-based protable handhelds, from gp2x upto the current lot of mips based ones like gkd350h and rg350. Those normally have the sdl window scaled by hardware to the screen, but no hardware scaling based overlay modes. This reflects in the default mode, desktop has it at overlay while portable usually has it at window.
I'll have more bug fixing on my backlog, but for now this is done.
