### ISSUE TITLE
Add support for .sg .sc .sf7 .mv file extensions for SG-1000/Othello Multivision

### ISSUE THREAD

**Issue by ghost** [irixxxx/picodrive#79]
@irixxxx can you please add .sg, .sc, .sf7, .mv file extensions for SG-1000/SC-3000/SF-7000/Othello Multivision ROMs.

.sg, .sc, .sf7 & .mv is about emulating SG-1000 mode in Master System Type "Auto"

**Comment by irixxxx** [comment]
For some sc3000 support I guess there should be keyboard support first, maybe in conjunction with PR #72.
I have no plans to "officially" support SF-7000 in the near future.
Is .mv correct for multivision? I can only find files with .omv as extension.

**Comment by irixxxx** [comment]
Done with cab84f2 but for .sf7 (no support for that planned in the near future).
