### ISSUE TITLE
[PocketGo2 v2 / PicoDrive 1.96] Sprite corruption in savestate preview

### ISSUE THREAD

**Issue by Drumaster78** [irixxxx/picodrive#8]
Hardware: PocketGo2 v2
O/S: Rogue FW 1.0.9 for PocketGo2 v2
Software: PicoDrive 1.96

Preview of savestates are corrupt and shows sprite mosaic. This occurs when ingame sprites currently use different frames from what the savestate preview shows.

1. Launch any game
2. Save your progression
3. Play a bit to display different sprite frames from what the savestate preview shows
4. Enter Load/Save state menu
5. Notice that the sprites are corrupt on savestate preview

Please see the attachment. Note that this issue does not occur with the fast 1.95 OPK I use.

![save_corrupt_sprites](https://user-images.githubusercontent.com/46139740/93711699-968d0080-fb50-11ea-837b-60d1b62bd480.png)

**Comment by irixxxx** [comment]
Fixed in e721f80

**Comment by Drumaster78** [comment]
Fixed verified.
