### ISSUE TITLE
Level 2 & 4 of Kolibri keep crashing.

### ISSUE THREAD

**Issue by sgoshaye** [irixxxx/picodrive#87]
Hello, I got picodrive for RetroArch on RP3+. On level 2 of Kolibri for 32x, whenever I move my character to certain areas, RetroArch crashes and takes me back to my homepage. There is constant crashing on level 2. I also asked someone else to verify this, and he said he eventually reached a point where the game keeps crashing.

**Comment by sgoshaye** [comment]
> What's in the retroarch log file?

I apologize for not providing it before. I am kind of new to this. 
[retroarch.log](https://github.com/irixxxx/picodrive/files/11565414/retroarch.log)

**Comment by sgoshaye** [comment]
Sending another log for testing purposes.
[retroarch.log](https://github.com/irixxxx/picodrive/files/11565580/retroarch.log)

**Comment by irixxxx** [comment]
There's no output from picodrive in the logs. Would you please increase the Core Logging Level in the Logging menu and try again?

**Comment by sgoshaye** [comment]
> There's no output from picodrive in the logs. Would you please increase the Core Logging Level in the Logging menu and try again?

I decided to try this on my Ubuntu 22.04 computer. It still crashes on level 2 of Kolibri. Here is the log. I set 0 for both, which is the highest level:

[retroarch.log](https://github.com/irixxxx/picodrive/files/11586059/retroarch.log)

**Comment by sgoshaye** [comment]
> There's no output from picodrive in the logs. Would you please increase the Core Logging Level in the Logging menu and try again?

I decided to try this on my Ubuntu 22.04 computer. It still crashes on level 2 of Kolibri. Here is the log. I was able to get the info when I ran "retroarch -v --log-file retroarch.log" in terminal.

This is the error I get when it crashes:

[INFO] [State]: Loading state "/home/sepehr/snap/retroarch/2005/.config/retroarch/states/Kolibri (USA, Europe).state", 678544 bytes.
[INFO] [State]: Saving state "RAM", 678544 bytes.
[libretro INFO] 09992:239: ssh2 drc: branch in DS @ 02093396
[libretro INFO] 10237:239: ssh2 drc: branch in DS @ 02092816
**Segmentation fault (core dumped)**

**Comment by irixxxx** [comment]
These 2 actually indicate a programming bug in the game itself - it violates the SH-2 manuals which prohibits branches in delay slots. It's most probably not related to the emulator crash.

Is this randomly happening, or is there some scenario where it always crashes? If so, could you provide a save file and instructions to reproduce, please?

**Comment by sgoshaye** [comment]
> These 2 actually indicate a programming bug in the game itself - it violates the SH-2 manuals which prohibits branches in delay slots. It's most probably not related to the emulator crash.
> 
> Is this randomly happening, or is there some scenario where it always crashes? If so, could you provide a save file and instructions to reproduce, please?

It uses a password system. The crashing happens when you fly around the stage, typically happening in the upper left of the screen in Stage 2:

2) Rescue 		- BLSCGFDP

A friend who got past the 2nd stage after endless crashing told me that freezing also occurs even moreso in the 4th stage. I decided to input a password and check it out, and I got a crash there too almost immediately. I will update the title of this thread to say Stage 2 and 4:

4)  Infestation 	- CZWTJFDG

I don't think it's a problem with the game because it was somewhat well-received and people would have mentioned the issue. It's by the developers of Ecco the Dolphin. If it came out on the Genesis, it would have been more well-known.

**Comment by irixxxx** [comment]
Is this also happening with the recompiler turned off?

**Comment by sgoshaye** [comment]
> Is this also happening with the recompiler turned off?

Yes, it's still happening with Dynamic Recompiler turned off on both Stage 2 & 4. I went ahead and tried it.

It took about 30 seconds to get Stage 2 to crash, but about 1 minute to get Stage 4 to crash.

**Comment by irixxxx** [comment]
I've tried for some time to reproduce your problem on a 64 bit ARM platform to no avail. Is the Pi3 still using 32 bit?

**Comment by sgoshaye** [comment]
> I've tried for some time to reproduce your problem on a 64 bit ARM platform to no avail. Is the Pi3 still using 32 bit?

I am using a Retroid Pocket 3+, which is known to play below Ps2 well. I am using Retroarch 1.15.0 stable. I downloaded aarch64.apk and have beaten several Ps1, SNES, etc. games with no problems.
It also crashes a lot of on my Ubuntu 22.04 system. It is also using Retroarch 1.15.0 stable on Ubuntu, which I got from the Snap Store.
I have not tested on my Windows computer yet.

I should have specified this before, sorry about that.

**Comment by irixxxx** [comment]
I'm not able to reproduce your problem with both of the passwords you provided. 
What exact version are you using? There should be a git revision behind the 1.99?
Could you build a core from the current [libretro master](https://github.com/libretro/picodrive), or else try a core built from the current master from [here](https://git.libretro.com/libretro/picodrive/-/pipelines/194772)?

**Comment by sgoshaye** [comment]
> I'm not able to reproduce your problem with both of the passwords you provided. What exact version are you using? There should be a git revision behind the 1.99? Could you build a core from the current [libretro master](https://github.com/libretro/picodrive), or else try a core built from the current master from [here](https://git.libretro.com/libretro/picodrive/-/pipelines/194772)?

It mentioned it in the RetroArch log. For retroid pocket 3+ the git is 1581ece. I downloaded it from the core list of RetroArch.

**Comment by sgoshaye** [comment]
> I'm not able to reproduce your problem with both of the passwords you provided. What exact version are you using? There should be a git revision behind the 1.99? Could you build a core from the current [libretro master](https://github.com/libretro/picodrive), or else try a core built from the current master from [here](https://git.libretro.com/libretro/picodrive/-/pipelines/194772)?

How can I check the git revision? In the logs for the Retroid Pocket 3+ it says Git: 1581ece.

**Comment by irixxxx** [comment]
It is normally displayed if you change from a running game to the menu, somewhere at the bottom. It should look like "PicoDrive 1.99-<revision>", with revision being a 7-digit hex number.

**Comment by sgoshaye** [comment]
> It is normally displayed if you change from a running game to the menu, somewhere at the bottom. It should look like `PicoDrive 1.99-<revision>`, with revision being a 7-digit hex number.

1.997119167

**Comment by irixxxx** [comment]
Your code is current, so it could not be that.
Could you give a more detailed description of what you are doing before the crash? Does pressing any button lead to this? Or flying into a certain area? Any observation would be helpful as it could help me reproducing it.

**Comment by irixxxx** [comment]
Ah, I just got the input it's related to the ROM image. The buggy one has this MD5:
6AF6207B1E67072A9104178130C61712
The image I pulled from my own cart has a different some and works fine. That explains why I couldn't trigger your bug.

I think I know what's going on. Going to try a fix later.

**Comment by sgoshaye** [comment]
> Ah, I just got the input it's related to the ROM image. The buggy one has this MD5: 6AF6207B1E67072A9104178130C61712 The image I pulled from my own cart has a different sum and works fine. That explains why I couldn't trigger your bug.
> 
> I think I know what's going on. Going to try a fix later.

Yes, I have the buggy rom with that MD5! I'm glad you've found the issue.

Do you have any email where I can contact you? I would like to ask something.

**Comment by irixxxx** [comment]
It's in the readme...

**Comment by irixxxx** [comment]
After converting my rom file from smd to bin (I'm using a modified super magic drive for pulling images), I have the same checksum as above. So, the roms aren't different. However, smd was treated a bit different in picodrive, leading to the bug being covered.
