### ISSUE TITLE
Picodrive psp 2.00_alpha1 dont load games

### ISSUE THREAD

**Issue by blackz1982** [irixxxx/picodrive#98]
![IMG_20231113_061042_229](https://github.com/irixxxx/picodrive/assets/1021857/c60c1453-6482-48e5-8f39-96f3d33925bd)
Hi, when I select "Load new game" menu item, the psp root opens without any folders(see attachment). When I click on the circle, the psp hangs and turns off after 30 seconds.

**Comment by irixxxx** [comment]
Hmm, it's working fine on PPSSPP. Is the ms0:/ path correct, or should the search be conducted elsewhere?

**Comment by irixxxx** [comment]
The crash is happening due to the list being completely empty. I'll fix that.
The list can only be empty if there are no directories or relevant files with one of the recognized extensions in the scanned directory. To check if the general scanning is working, put any zip file in that directory and see if it occurs in picodrive.

**Comment by blackz1982** [comment]
I put the game in a zip archive in the root of the memory card. And yes, it is displayed and you can run it. But, I have folders in the root of the memory card, they can't not be there. 
Here is an example of how the root of the memory card looks like in picodrive 1.92.

**Comment by irixxxx** [comment]
Are you seeing more files if you press square?

**Comment by blackz1982** [comment]
If there is a zip archive in the root of the memory card, then yes, the folders are visible when you press the square. If there is no zip archive, the psp hangs when you click on the square.

**Comment by irixxxx** [comment]
There is a new psp version on the release page. Could you please check if that fixes the problem?

**Comment by blackz1982** [comment]
It works in principle. But there are some flaws.
1) When you click on "Load new game" the buttons assignment (circle -select, X-back and so on) is not displayed. 
2) If you start the emulator for the first time and exit immediately, "LastUsedROM=ms0:/" is added to the config2.cfg file. After that, when you start the emulator for the second time and try to start the game, the emulator hangs when you press any button as in the previous build. If you select any subfolder, start the game and for example then saved "LastUsedROM=ms0:/Roms/Md" then at the next start everything will be fine.
3) But then you can not return to the root of the memory card. 

And also from game to game there are image artifacts similar to tearing. And if you turn on vsync everything becomes much worse. Very well it is noticeable on the game Lost world

**Comment by irixxxx** [comment]
I've fixed a bug in pspsdk. The file selector should now behave.

**Comment by irixxxx** [comment]
Could you please try again with the latest psp artifact from the actions tab?

**Comment by irixxxx** [comment]
Closing this as testing by @ftrujy seems to show it is now working correctly. If you still find some problems with the file selection please reopen.
